# =============================================================================
# Pokédex Voice Over — KIF Mod
# =============================================================================
# Reads Pokédex entries aloud in the style of Dexter, the classic Pokémon
# anime Pokédex narrator, whenever a Pokédex entry page is opened.
#
# Supports both regular Pokémon and every fused variant.
#
# AUDIO FILES
# -----------
# Audio files must be placed in:
#   <game root>/Audio/SE/Pokedex/
#
# Naming convention:
#   dex_SPECIES.ogg              — regular Pokémon  (e.g. dex_BULBASAUR.ogg)
#   dex_SPECIES1_SPECIES2.ogg    — fused Pokémon    (e.g. dex_BULBASAUR_CHARMANDER.ogg)
#
# A duration manifest generated by tools/generate_voices.py is read from:
#   <game root>/Audio/SE/Pokedex/dex_durations.json
# This is used to time sequential playback for fusions without a custom audio
# file (the mod plays each base species entry back-to-back).
#
# Run  tools/generate_voices.py  from the repository to generate these files
# from your game's PBS data.
# =============================================================================

module PokedexVoiceOver
  MOD_ID = "pokedex_voice_over"

  # Subfolder inside Audio/SE/ where all Pokédex voice-over audio lives.
  AUDIO_SUBDIR = "Pokedex"

  # Fallback playback duration (seconds) used when dex_durations.json has no
  # entry for a given file.  5 seconds covers most Pokédex entries comfortably.
  SEQUENTIAL_DURATION_FALLBACK = 5.0

  # -------------------------------------------------------------------------
  # Settings helpers
  # -------------------------------------------------------------------------

  def self.settings
    ($mod_manager_settings || {})[MOD_ID] || {}
  end

  def self.enabled?
    settings.fetch("enabled", true)
  end

  def self.volume
    settings.fetch("volume", 80).to_i.clamp(0, 100)
  end

  def self.play_on_page_change?
    settings.fetch("play_on_page_change", false)
  end

  # -------------------------------------------------------------------------
  # Duration manifest (loaded lazily, cached)
  # -------------------------------------------------------------------------

  def self.durations
    return @durations if @durations
    path = "Audio/SE/#{AUDIO_SUBDIR}/dex_durations.json"
    @durations = begin
      if FileTest.exist?(path)
        require "json"
        JSON.parse(File.read(path))
      else
        {}
      end
    rescue StandardError
      {}
    end
  end

  # -------------------------------------------------------------------------
  # Species helpers
  # -------------------------------------------------------------------------

  # Convert a species value (Symbol, Integer, or String) to an UPPER_CASE
  # internal-name string suitable for use in a filename.
  def self.species_str(species)
    return nil if species.nil?
    # Integer 0 means "no species" in older Essentials versions
    return nil if species.is_a?(Integer) && species <= 0

    if species.is_a?(Symbol)
      return species.to_s.upcase
    end

    if species.is_a?(Integer)
      # Try to resolve via GameData (Essentials v19+)
      begin
        return GameData::Species.get(species).id.to_s.upcase
      rescue StandardError
        nil
      end
      # Fallback: try PBSpecies constant name (Essentials v18)
      begin
        name = getConstantName(PBSpecies, species)
        return name.upcase if name
      rescue StandardError
        nil
      end
      return species.to_s
    end

    return species.to_s.upcase
  end

  # -------------------------------------------------------------------------
  # Playback helpers
  # -------------------------------------------------------------------------

  # Return true if an audio file for *bare_name* (without Audio/SE/ prefix)
  # exists on disk.  FileTest.exist? uses the real filesystem path so we must
  # supply the full path including the subdirectory and extension.
  def self._audio_exists?(bare_name)
    [".ogg", ".wav", ".mp3"].any? do |ext|
      FileTest.exist?("Audio/SE/#{bare_name}#{ext}")
    end
  end

  # Play a single audio file (bare_name is relative to Audio/SE/).
  # Stops any currently playing SE first.
  def self._play_bare(bare_name)
    Audio.se_stop
    # RGSS resolves paths relative to Audio/SE/ — the AUDIO_SUBDIR prefix is
    # enough; no "Audio/SE/" prefix needed here.
    Audio.se_play(bare_name, volume, 100)
  end

  # -------------------------------------------------------------------------
  # Playback
  # -------------------------------------------------------------------------

  # Play the voice-over for *species* (and optionally its fusion partner).
  #
  # For fused Pokémon:
  #   1. If a dedicated fusion audio file exists, play it directly.
  #   2. Otherwise, if both base-species files exist, play them sequentially
  #      in a background thread (head first, then body after the head
  #      finishes — timed using the dex_durations.json manifest).
  #
  # Silently returns if no matching audio can be found.
  def self.play(species, fused_species = nil)
    return unless enabled?

    base = species_str(species)
    return unless base

    fused = species_str(fused_species)

    # Advance the generation counter to invalidate any in-progress sequential
    # playback thread without forcibly killing it.
    @playback_gen = (@playback_gen || 0) + 1

    if fused
      fusion_bare = "#{AUDIO_SUBDIR}/dex_#{base}_#{fused}"

      if _audio_exists?(fusion_bare)
        # Dedicated fusion file — play it directly
        begin
          _play_bare(fusion_bare)
        rescue StandardError => e
          p "[PokedexVoiceOver] Audio playback error: #{e.message}" if $DEBUG
        end
      else
        # No custom fusion entry — fall back to sequential base-species playback
        bare_head = "#{AUDIO_SUBDIR}/dex_#{base}"
        bare_body = "#{AUDIO_SUBDIR}/dex_#{fused}"

        if _audio_exists?(bare_head) && _audio_exists?(bare_body)
          head_duration = (durations["dex_#{base}.ogg"] || SEQUENTIAL_DURATION_FALLBACK).to_f
          vol = volume        # capture for thread closure
          my_gen = @playback_gen  # snapshot so the thread can self-cancel
          begin
            Audio.se_stop
            Thread.new do
              begin
                Audio.se_play(bare_head, vol, 100)
                # Sleep in small increments so we respond promptly to new
                # play/stop calls (which bump @playback_gen).
                elapsed = 0.0
                step = 0.1
                while elapsed < head_duration
                  break if @playback_gen != my_gen
                  sleep(step)
                  elapsed += step
                end
                Audio.se_play(bare_body, vol, 100) if @playback_gen == my_gen
              rescue StandardError => e
                p "[PokedexVoiceOver] Sequential playback error: #{e.message}" if $DEBUG
              end
            end
          rescue StandardError => e
            p "[PokedexVoiceOver] Audio playback error: #{e.message}" if $DEBUG
          end
        end
      end
    else
      bare = "#{AUDIO_SUBDIR}/dex_#{base}"
      return unless _audio_exists?(bare)

      begin
        _play_bare(bare)
      rescue StandardError => e
        p "[PokedexVoiceOver] Audio playback error: #{e.message}" if $DEBUG
      end
    end
  end

  # Stop any playing voice-over, including any pending sequential playback.
  # Bumping @playback_gen causes any running playback thread to exit cleanly.
  def self.stop
    @playback_gen = (@playback_gen || 0) + 1
    begin
      Audio.se_stop
    rescue StandardError => e
      p "[PokedexVoiceOver] Audio stop error: #{e.message}" if $DEBUG
    end
  end
end

# =============================================================================
# Hook into PokemonPokedexInfo_Scene
# =============================================================================
# We alias three methods:
#   pbStartScene  — fires once when the Pokédex entry scene opens
#   pbShowPage    — fires whenever the displayed page changes
#   pbEndScene    — fires when the scene closes (so we can stop the audio)
#
# The description/entry page is typically page index 0 in Pokémon Infinite
# Fusion.  Adjust ENTRY_PAGE below if your build uses a different index.
# =============================================================================

if defined?(PokemonPokedexInfo_Scene)
  class PokemonPokedexInfo_Scene
    POKEDEX_VO_ENTRY_PAGE = 0   # page index that shows the Pokédex description

    # Helper: read the current species + fusion partner from scene state.
    # Tries several variable names used across PIF / KIF versions.
    def pokedex_vo_current_species
      head  = @species rescue nil
      # Fusion partner: different KIF / PIF versions use different names
      fused = begin
                @fusedSpecies
              rescue StandardError
                begin
                  @dexSpecies2
                rescue StandardError
                  begin
                    @speciesFused
                  rescue StandardError
                    nil
                  end
                end
              end
      [head, fused]
    end

    # ------------------------------------------------------------------
    # pbStartScene  — play when the Pokédex entry scene first opens
    # ------------------------------------------------------------------
    if method_defined?(:pbStartScene)
      alias dex_vo_orig_pbStartScene pbStartScene

      def pbStartScene(*args)
        dex_vo_orig_pbStartScene(*args)
        # After the scene is set up, play the voice for the entry page
        page = @page rescue POKEDEX_VO_ENTRY_PAGE
        if page == POKEDEX_VO_ENTRY_PAGE
          head, fused = pokedex_vo_current_species
          PokedexVoiceOver.play(head, fused)
        end
      end
    end

    # ------------------------------------------------------------------
    # pbShowPage  — play (optionally) when returning to the entry page
    # ------------------------------------------------------------------
    if method_defined?(:pbShowPage)
      alias dex_vo_orig_pbShowPage pbShowPage

      def pbShowPage(page, *args)
        prev_page = @page rescue nil
        dex_vo_orig_pbShowPage(page, *args)

        # Only play when the user navigates TO the entry page, not on every
        # call.  We also honour the "play_on_page_change" setting so players
        # who do not want the voice to restart on every revisit can turn it
        # off.
        if page == POKEDEX_VO_ENTRY_PAGE && prev_page != POKEDEX_VO_ENTRY_PAGE
          if PokedexVoiceOver.play_on_page_change?
            head, fused = pokedex_vo_current_species
            PokedexVoiceOver.play(head, fused)
          end
        end
      end
    end

    # ------------------------------------------------------------------
    # pbEndScene  — stop the voice when the scene closes
    # ------------------------------------------------------------------
    if method_defined?(:pbEndScene)
      alias dex_vo_orig_pbEndScene pbEndScene

      def pbEndScene(*args)
        PokedexVoiceOver.stop
        dex_vo_orig_pbEndScene(*args)
      end
    end
  end
end
