# =============================================================================
# Pokédex Voice Over — KIF Mod
# =============================================================================
# Reads Pokédex entries aloud in the style of Dexter, the classic Pokémon
# anime Pokédex narrator, whenever a Pokédex entry page is opened.
#
# Supports both regular Pokémon and every fused variant.
#
# AUDIO FILES
# -----------
# Audio files must be placed in:
#   <game root>/Audio/SE/Pokedex/
#
# Naming convention:
#   dex_SPECIES.ogg              — regular Pokémon  (e.g. dex_BULBASAUR.ogg)
#   dex_SPECIES1_SPECIES2.ogg    — fused Pokémon    (e.g. dex_BULBASAUR_CHARMANDER.ogg)
#
# A duration manifest generated by tools/generate_voices.py is read from:
#   <game root>/Audio/SE/Pokedex/dex_durations.json
# This is used to time sequential playback for fusions without a custom audio
# file (the mod plays each base species entry back-to-back).
#
# An entry text map generated by tools/generate_voices.py is read from:
#   <game root>/Audio/SE/Pokedex/dex_entry_map.json
# This maps each audio file to the Pokédex entry text it was generated from,
# allowing the mod to play the correct variant when multiple entries exist.
#
# Run  tools/generate_voices.py  from the repository to generate these files
# from your game's PBS data.
#
# DIAGNOSTIC LOG
# --------------
# The mod writes a diagnostic log to:
#   <game root>/Mods/pokedex_voice_over/debug.log
#
# Check this file if audio does not play — it records every hook call,
# species detection attempt, file-existence check, and playback call so
# you can see exactly where the process stops.
# =============================================================================

module PokedexVoiceOver
  MOD_ID = "pokedex_voice_over"

  # Subfolder inside Audio/SE/ where all Pokédex voice-over audio lives.
  AUDIO_SUBDIR = "Pokedex"

  # Fallback playback duration (seconds) used when dex_durations.json has no
  # entry for a given file.  5 seconds covers most Pokédex entries comfortably.
  SEQUENTIAL_DURATION_FALLBACK = 5.0

  # Delay (seconds) before voice-over playback begins, allowing the Pokémon's
  # cry to finish before the Pokédex entry is read aloud.
  CRY_DELAY = 0.5

  # Diagnostic log file — always written so users can report issues.
  LOG_FILE = "Mods/pokedex_voice_over/debug.log"

  # -------------------------------------------------------------------------
  # Diagnostic logging — writes to LOG_FILE on every significant event
  # -------------------------------------------------------------------------

  def self.log(msg)
    line = "[#{Time.now.strftime('%H:%M:%S')}] #{msg}"
    File.open(LOG_FILE, "a") { |f| f.puts(line) } rescue nil
  end

  # -------------------------------------------------------------------------
  # Settings helpers
  # -------------------------------------------------------------------------

  def self.settings
    ($mod_manager_settings || {})[MOD_ID] || {}
  end

  def self.enabled?
    if defined?(ModSettingsMenu)
      val = ModSettingsMenu.get(:pokedex_vo_enabled)
      return val == 1 if !val.nil?
    end
    settings.fetch("enabled", true)
  end

  def self.volume
    if defined?(ModSettingsMenu)
      val = ModSettingsMenu.get(:pokedex_vo_volume)
      return val.to_i.clamp(0, 100) if !val.nil?
    end
    settings.fetch("volume", 80).to_i.clamp(0, 100)
  end

  def self.play_on_page_change?
    if defined?(ModSettingsMenu)
      val = ModSettingsMenu.get(:pokedex_vo_replay_on_page_change)
      return val == 1 if !val.nil?
    end
    settings.fetch("play_on_page_change", false)
  end

  def self.mute_music?
    if defined?(ModSettingsMenu)
      val = ModSettingsMenu.get(:pokedex_vo_mute_music)
      return val == 1 if !val.nil?
    end
    settings.fetch("mute_music", true)
  end

  # -------------------------------------------------------------------------
  # Duration manifest (loaded lazily, cached)
  # -------------------------------------------------------------------------

  def self.durations
    return @durations if @durations
    path = "Audio/SE/#{AUDIO_SUBDIR}/dex_durations.json"
    @durations = begin
      if FileTest.exist?(path)
        require "json"
        JSON.parse(File.read(path))
      else
        {}
      end
    rescue StandardError
      {}
    end
  end

  # -------------------------------------------------------------------------
  # Entry map — maps audio file stems to their Pokédex entry texts
  # (loaded lazily, cached).  Used to match the displayed text to the
  # correct audio variant instead of picking one at random.
  # -------------------------------------------------------------------------

  def self.entry_map
    return @entry_map if @entry_map
    path = "Audio/SE/#{AUDIO_SUBDIR}/dex_entry_map.json"
    @entry_map = begin
      if FileTest.exist?(path)
        require "json"
        data = JSON.parse(File.read(path))
        log("  Loaded entry map: #{data.size} entries from #{path}")
        data
      else
        log("  Entry map not found: #{path}")
        {}
      end
    rescue StandardError => e
      log("  Entry map load error: #{e.message}")
      {}
    end
  end

  # -------------------------------------------------------------------------
  # BGM mute / restore helpers
  # -------------------------------------------------------------------------

  # Save the currently playing BGM and fade it out.
  # Called when the Pokédex scene opens so the voice-over (and the browsing
  # experience in general) is not drowned out by background music.
  # Does nothing when the mute_music setting is disabled.
  def self.save_and_mute_bgm
    return unless mute_music?
    return if @bgm_muted  # already muted — don't overwrite the saved BGM
    begin
      @saved_bgm = $game_system.playing_bgm.clone rescue nil
      Audio.bgm_fade(500) rescue nil
      @bgm_muted = true
      log("  BGM muted (saved: #{@saved_bgm.inspect})")
    rescue => e
      log("  BGM mute failed: #{e.message}")
      @bgm_muted = false
    end
  end

  # Restore the previously saved BGM.  Safe to call multiple times — does
  # nothing if no BGM was muted.
  def self.restore_bgm
    return unless @bgm_muted
    begin
      if @saved_bgm
        begin
          $game_system.bgm_play(@saved_bgm)
        rescue
          Audio.bgm_play(@saved_bgm.name, @saved_bgm.volume, @saved_bgm.pitch) rescue nil
        end
        log("  BGM restored: #{@saved_bgm.inspect}")
      end
      @bgm_muted = false
      @saved_bgm = nil
    rescue => e
      log("  BGM restore failed: #{e.message}")
    end
  end

  # -------------------------------------------------------------------------
  # Species helpers
  # -------------------------------------------------------------------------

  # Convert a species value (Symbol, Integer, or String) to an UPPER_CASE
  # internal-name string suitable for use in a filename.
  def self.species_str(species)
    return nil if species.nil?
    # Integer 0 means "no species" in older Essentials versions
    return nil if species.is_a?(Integer) && species <= 0

    if species.is_a?(Symbol)
      return species.to_s.upcase
    end

    if species.is_a?(Integer)
      # Try to resolve via GameData (Essentials v19+)
      begin
        return GameData::Species.get(species).id.to_s.upcase
      rescue StandardError
        nil
      end
      # Fallback: try PBSpecies constant name (Essentials v18)
      begin
        name = getConstantName(PBSpecies, species)
        return name.upcase if name
      rescue StandardError
        nil
      end
      # Last resort: iterate GameData looking for matching id_number
      begin
        if defined?(GameData::Species)
          GameData::Species.each do |sp|
            if sp.respond_to?(:id_number) && sp.id_number == species
              log("  species_str: resolved #{species} to #{sp.id.inspect} via id_number scan")
              return sp.id.to_s.upcase
            end
          end
        end
      rescue StandardError
        nil
      end
      log("  WARNING: species_str falling back to raw integer #{species} — no name resolution succeeded")
      return species.to_s
    end

    return species.to_s.upcase
  end

  # Upper bound for "regular" (non-fusion) species IDs when scanning GameData.
  # Fusion composite IDs (head * NB_POKEMON + body) are well above this.
  MAX_BASE_SPECIES_ID = 10_000

  # -------------------------------------------------------------------------
  # NB_POKEMON helper — cached lookup with multiple fallbacks
  # -------------------------------------------------------------------------

  def self.nb_pokemon
    return @nb_pokemon if @nb_pokemon
    nb = nil
    nb = NB_POKEMON if defined?(NB_POKEMON)
    nb ||= (Settings::NB_POKEMON rescue nil) if defined?(Settings)
    nb ||= (Pokemon::NB_POKEMON rescue nil) if defined?(Pokemon)
    nb ||= (PBSpecies.maxValue rescue nil) if defined?(PBSpecies)
    # Fallback: count GameData species entries (non-fusion max ID)
    if nb.nil? && defined?(GameData::Species)
      begin
        max_id = 0
        GameData::Species.each do |sp|
          n = sp.id_number if sp.respond_to?(:id_number)
          max_id = n if n.is_a?(Integer) && n > max_id && n < MAX_BASE_SPECIES_ID
        end
        nb = max_id if max_id > 0
        log("  nb_pokemon via GameData scan: #{nb}") if nb
      rescue StandardError => e
        log("  nb_pokemon GameData scan failed: #{e.message}")
      end
    end
    @nb_pokemon = nb if nb
    nb
  end

  # -------------------------------------------------------------------------
  # Playback helpers
  # -------------------------------------------------------------------------

  # Return true if an audio file for *bare_name* (without Audio/SE/ prefix)
  # exists on disk.  FileTest.exist? uses the real filesystem path so we must
  # supply the full path including the subdirectory and extension.
  def self._audio_exists?(bare_name)
    [".ogg", ".wav", ".mp3"].any? do |ext|
      path = "Audio/SE/#{bare_name}#{ext}"
      found = FileTest.exist?(path)
      log("  _audio_exists? #{path} => #{found}")
      found
    end
  end

  # Find all variant audio files for a given base bare_name.
  # Returns a list of bare names (relative to Audio/SE/) including the primary
  # file and any variant files (e.g. dex_BULBASAUR_CHARMANDER_v2).
  #
  # Variant naming convention:
  #   Pokedex/dex_SPECIES.ogg          — primary
  #   Pokedex/dex_SPECIES_v2.ogg       — variant 2
  #   Pokedex/dex_SPECIES_v3.ogg       — variant 3
  #   Pokedex/dex_SP1_SP2_v2.ogg       — fusion variant 2
  def self._find_variants(bare_name)
    variants = []
    variants << bare_name if _audio_exists?(bare_name)

    # Check for _v2, _v3, ... up to a reasonable limit
    n = 2
    max_variants = 20
    loop do
      break if n > max_variants
      candidate = "#{bare_name}_v#{n}"
      if _audio_exists?(candidate)
        variants << candidate
        n += 1
      else
        break
      end
    end

    log("  _find_variants(#{bare_name}) => #{variants.length} file(s)")
    variants
  end

  # Normalize text for comparison: strip, downcase, collapse whitespace.
  def self._normalize_text(text)
    return "" unless text.is_a?(String)
    text.strip.downcase.gsub(/\s+/, " ")
  end

  # Given a list of variant bare names and the displayed entry text,
  # find the variant whose generated text matches the displayed text.
  # Returns the matching bare name, or nil if no match found.
  def self._match_variant(variants, displayed_text)
    return nil unless displayed_text.is_a?(String) && !displayed_text.strip.empty?
    return nil if entry_map.empty?

    norm_displayed = _normalize_text(displayed_text)
    return nil if norm_displayed.empty?
    log("  _match_variant: trying to match (#{norm_displayed.length} chars): #{norm_displayed[0, 60]}...")

    # Try exact normalized match
    variants.each do |variant_bare|
      stem = variant_bare.sub(/\A#{Regexp.escape(AUDIO_SUBDIR)}\//, "")
      map_text = entry_map[stem]
      next unless map_text
      if _normalize_text(map_text) == norm_displayed
        log("  _match_variant: exact match => #{variant_bare}")
        return variant_bare
      end
    end

    # Try prefix match (first 40 normalized characters)
    prefix_len = 40
    if norm_displayed.length >= prefix_len
      norm_prefix = norm_displayed[0, prefix_len]
      variants.each do |variant_bare|
        stem = variant_bare.sub(/\A#{Regexp.escape(AUDIO_SUBDIR)}\//, "")
        map_text = entry_map[stem]
        next unless map_text
        if _normalize_text(map_text).start_with?(norm_prefix)
          log("  _match_variant: prefix match => #{variant_bare}")
          return variant_bare
        end
      end
    end

    log("  _match_variant: no match found")
    nil
  end

  # Play a single audio file (bare_name is relative to Audio/SE/).
  # Stops any currently playing SE first.
  #
  # Tries the bare path first (standard RGSS resolves relative to Audio/SE/),
  # then falls back to the full "Audio/SE/" prefixed path in case the engine
  # needs it (some MKXP builds behave differently).
  def self._play_bare(bare_name)
    Audio.se_stop
    log("  _play_bare: Audio.se_play('#{bare_name}', #{volume}, 100)")
    begin
      Audio.se_play(bare_name, volume, 100)
      return
    rescue StandardError => e
      log("  _play_bare: bare path failed (#{e.class}: #{e.message})")
    end
    # Fallback: try with "Audio/SE/" prefix
    full = "Audio/SE/#{bare_name}"
    log("  _play_bare: retrying with Audio.se_play('#{full}', #{volume}, 100)")
    begin
      Audio.se_play(full, volume, 100)
    rescue StandardError => e
      log("  _play_bare: full path also failed (#{e.class}: #{e.message})")
    end
  end

  # -------------------------------------------------------------------------
  # Playback
  # -------------------------------------------------------------------------

  # Play the voice-over for *species* (and optionally its fusion partner).
  #
  # For fused Pokémon:
  #   1. If a dedicated fusion audio file exists, play it directly.
  #      If variant files exist (_v2, _v3…), the one matching the
  #      *displayed_text* is chosen when possible; falls back to random.
  #   2. Otherwise, if both base-species files exist, play them sequentially
  #      in a background thread (head first, then body after the head
  #      finishes — timed using the dex_durations.json manifest).
  #
  # Returns silently if no matching audio can be found.
  def self.play(species, fused_species = nil, displayed_text = nil)
    log("play() called — enabled=#{enabled?}, species=#{species.inspect}, fused=#{fused_species.inspect}, text=#{displayed_text ? displayed_text[0,40].inspect : 'nil'}")
    return unless enabled?

    base = species_str(species)
    log("  base species_str => #{base.inspect}")
    return unless base

    fused = species_str(fused_species)
    log("  fused species_str => #{fused.inspect}")

    # Advance the generation counter to invalidate any in-progress sequential
    # playback thread without forcibly killing it.
    @playback_gen = (@playback_gen || 0) + 1
    my_gen = @playback_gen  # snapshot so the thread can self-cancel

    # All playback goes through a background thread so the CRY_DELAY and any
    # sequential waits never freeze the game loop.
    begin
      Thread.new do
        begin
          # Wait for the Pokémon's cry to finish before reading the entry.
          _interruptible_sleep(CRY_DELAY, my_gen)
          next if @playback_gen != my_gen

          if fused
            fusion_bare = "#{AUDIO_SUBDIR}/dex_#{base}_#{fused}"

            # Check for the primary fusion file and any variants
            fusion_variants = _find_variants(fusion_bare)

            # Try reversed ordering (dex_BODY_HEAD) if forward not found.
            # KIF may encode fusions with head/body in either order depending
            # on version and how the composite ID is decomposed.
            reversed_bare = nil
            if fusion_variants.empty?
              reversed_bare = "#{AUDIO_SUBDIR}/dex_#{fused}_#{base}"
              fusion_variants = _find_variants(reversed_bare)
              if fusion_variants.any?
                log("  Using reversed fusion ordering: #{reversed_bare}")
                fusion_bare = reversed_bare
              end
            end

            if fusion_variants.any?
              matched = _match_variant(fusion_variants, displayed_text)
              chosen = matched || fusion_variants.sample
              log("  Playing fusion audio: #{chosen} (from #{fusion_variants.length} variant(s), matched=#{!matched.nil?})")
              _play_bare(chosen)
            else
              # No custom fusion entry — fall back to sequential base-species playback
              bare_head = "#{AUDIO_SUBDIR}/dex_#{base}"
              bare_body = "#{AUDIO_SUBDIR}/dex_#{fused}"

              if _audio_exists?(bare_head) && _audio_exists?(bare_body)
                log("  Playing sequential: #{bare_head} then #{bare_body}")
                head_duration = (durations["dex_#{base}.ogg"] || SEQUENTIAL_DURATION_FALLBACK).to_f
                Audio.se_stop
                Audio.se_play(bare_head, volume, 100)
                _interruptible_sleep(head_duration, my_gen)
                if @playback_gen == my_gen
                  Audio.se_play(bare_body, volume, 100)
                end
              else
                log("  No fusion or sequential audio available — skipping")
              end
            end
          else
            bare = "#{AUDIO_SUBDIR}/dex_#{base}"

            # Check for the primary file and any variants
            variants = _find_variants(bare)
            if variants.empty?
              log("  No audio file found — skipping")
              next
            end

            matched = _match_variant(variants, displayed_text)
            chosen = matched || variants.sample
            log("  Playing species audio: #{chosen} (from #{variants.length} variant(s), matched=#{!matched.nil?})")
            _play_bare(chosen)
          end
        rescue StandardError => e
          PokedexVoiceOver.log("  Playback thread error: #{e.class}: #{e.message}")
        end
      end
    rescue StandardError => e
      log("  Thread creation error: #{e.class}: #{e.message}")
    end
  end

  # Sleep in small increments so we respond promptly to new play/stop calls
  # (which bump @playback_gen).  Returns early if the generation changes.
  def self._interruptible_sleep(duration, gen)
    elapsed = 0.0
    step = 0.1
    while elapsed < duration
      break if @playback_gen != gen
      sleep(step)
      elapsed += step
    end
  end

  # Stop any playing voice-over, including any pending sequential playback.
  # Bumping @playback_gen causes any running playback thread to exit cleanly.
  # NOTE: BGM is now managed by the scene hooks (muted on open, restored on
  # close), so stop only handles SE playback.
  def self.stop
    @playback_gen = (@playback_gen || 0) + 1
    begin
      Audio.se_stop
    rescue StandardError => e
      log("stop error: #{e.class}: #{e.message}")
    end
  end
end

# =============================================================================
# Hook into PokemonPokedexInfo_Scene
# =============================================================================
# We alias three methods:
#   pbStartScene  — fires once when the Pokédex entry scene opens
#   pbShowPage    — fires whenever the displayed page changes
#   pbEndScene    — fires when the scene closes (so we can stop the audio)
#
# The description/entry page is typically page index 0 in Pokémon Infinite
# Fusion.  Adjust ENTRY_PAGE below if your build uses a different index.
#
# KNOWN BUG FIXES (v1.10.0)
# --------------------------
# - KIF scene methods (getCustomDexEntry, getCustomEntryText, getAIDexEntry)
#   now called with correct arguments (species/composite ID) instead of zero
#   args.  Uses arity-aware fallback to try multiple argument sets.
# - GameData composite lookup now cross-checks fusion text against the head
#   species' base entry; discards the result when they match (indicating the
#   lookup returned stale base-species text, not the fusion's custom entry).
# - New @sprites overlay text extraction strategy reads displayed entry text
#   from KIF's UI text windows when other methods fail.
# - pbGetMessage now also tried with the composite species ID for fusions.
# - Double playback eliminated: navigation hooks (pbGoToNext/pbGoToPrevious)
#   and pbStartScene set flags (@dex_vo_nav_played / @dex_vo_scene_played)
#   that drawPage/pbShowPage check and clear, preventing the second play()
#   call that previously occurred on every navigation or scene open.
#
# KNOWN BUG FIXES (v1.9.0)
# -------------------------
# - CRY_DELAY reduced from 1.0s to 0.5s — voice reads sooner after opening.
# - Fusion species detection: composite-ID decomposition now also tries
#   @dummyPokemon.id_number when .species returns a Symbol, fixing fusions
#   that returned the wrong species name or played the wrong audio file.
# - species_str: added id_number scan fallback when GameData::Species.get()
#   and PBSpecies both fail for an integer ID, with warning log when falling
#   back to raw number.
# - Scrolling voice: pbGoToNext/pbGoToPrevious no longer gate playback on
#   @page == ENTRY_PAGE (the page ivar could be stale after scrolling).
#   Voice now always triggers on navigation.
# - drawPage and pbShowPage hooks now detect species changes (not just page
#   changes), so voice plays reliably after scrolling even if pbGoToNext
#   fires with stale state or is bypassed by the engine.
#
# KNOWN BUG FIXES (v1.8.0)
# -------------------------
# - Species detection now prioritizes @dummyPokemon (refreshed by
#   pbUpdateDummyPokemon) over @species, which may be stale after scrolling
#   via pbGoToNext/pbGoToPrevious.  @dexlist[@index] is also checked before
#   the potentially-stale @species ivar.
# - Fusion audio lookup now tries both orderings (dex_HEAD_BODY and
#   dex_BODY_HEAD) since KIF may encode fusions either way depending on
#   version and composite-ID decomposition order.
# - Fusion partner is now extracted from @dummyPokemon attributes (.fused,
#   .fused_species, etc.) before falling back to separate ivars.
# - Text detection now prioritizes @dummyPokemon attributes and KIF scene
#   methods (getCustomDexEntry, etc.) over instance variable scanning, which
#   was often returning stale data after navigation.
# - Navigation state tracking: pbGoToNext/pbGoToPrevious now log when the
#   detected species hasn't changed (stale-state warning) to help diagnose
#   remaining issues.
# - Enhanced diagnostic logging shows @dummyPokemon capabilities, species
#   cross-checks, and all detection strategy results.
#
# KNOWN BUG FIXES (v1.7.0)
# -------------------------
# - Scrolling between Pokémon entries (pbGoToNext / pbGoToPrevious) now
#   triggers voice-over playback for the newly displayed entry.  Previously
#   only manually selecting a Pokémon via the action button would play.
# - Fusion Pokédex entry text detection now uses KIF-specific scene methods
#   (getCustomDexEntry, getCustomEntryText) and composite-ID GameData lookup,
#   fixing fusions that were not read aloud or played the wrong variant.
# - NB_POKEMON detection now uses a centralized helper with additional
#   fallbacks (Settings::NB_POKEMON, GameData species scan) so fusion
#   species decomposition works in more KIF builds.
# - @dummyPokemon is now checked as a text source for dex entry text.
#
# KNOWN BUG FIXES (v1.6.0)
# -------------------------
# - Variant audio selection now matches the displayed Pokédex entry text
#   instead of picking a random variant.  Uses dex_entry_map.json (generated
#   by tools/generate_voices.py) to look up which audio file corresponds to
#   the text the game is currently showing.  Falls back to random selection
#   when the displayed text cannot be determined or matched.
#
# KNOWN BUG FIXES (v1.5.0)
# -------------------------
# - BGM is now muted as soon as the Pokédex *menu* opens (PokemonPokedex_Scene)
#   rather than when opening an individual entry.  Music resumes only when
#   closing the Pokédex menu completely.
# - A 1-second delay is now applied before the voice-over plays, so the
#   Pokémon's cry is heard first before the Pokédex entry audio begins.
#
# KNOWN BUG FIXES (v1.4.0)
# -------------------------
# - Music is now muted as soon as the Pokédex scene opens (regardless of
#   which page is shown) and restored when the scene closes.  Previously
#   music was only muted when a voice-over played on the entry page.
# - Fused Pokémon with multiple Pokédex entries are now supported.  The mod
#   detects variant audio files (dex_SP1_SP2_v2.ogg, _v3.ogg, …) and
#   randomly selects one each time — matching the game's behaviour of
#   choosing a random entry for fusions.
#
# KNOWN BUG FIXES (v1.3.0)
# -------------------------
# - Fused Pokémon without custom dex entries now play correctly.  KIF encodes
#   fused species as a single integer (head_id * NB_POKEMON + body_id).
#   pokedex_vo_current_species now detects and decomposes these IDs before
#   falling back to separate fused-species ivar lookups.
# - BGM is automatically muted when voice-over starts and restored when it
#   stops (or the Pokédex is closed).  Controlled by the new mute_music setting.
# - All settings are now also registered in the Mod Settings menu (Interface
#   category) when Stonewall's Mod Settings mod is installed.
#
# KNOWN BUG FIXES (v1.2.0)
# -------------------------
# - POKEDEX_VO_ENTRY_PAGE was 0 but KIF uses 1-based page indices — the
#   entry/description page is page 1.  Changed default to 1.
# - pbShowPage does not exist in KIF — added a fallback hook on drawPage
#   so the "play_on_page_change" feature works in KIF builds.
#
# KNOWN BUG FIXES (v1.1.0)
# -------------------------
# - Instance-variable access (e.g. `@page rescue fallback`) does NOT raise
#   in Ruby — undefined ivars return nil silently.  Replaced with explicit
#   nil-checks so the fallback values are actually used.
# - Fusion-species fallback chain now uses instance_variable_defined? so
#   alternate variable names (@dexSpecies2, etc.) are actually tried.
# - Species detection now also checks @dexlist[@index] (common Essentials
#   pattern) as a fallback when @species is not set.
# =============================================================================

PokedexVoiceOver.log("=" * 60)
PokedexVoiceOver.log("Pokédex Voice Over mod loading...")
PokedexVoiceOver.log("  Ruby version: #{RUBY_VERSION rescue 'unknown'}")
PokedexVoiceOver.log("  defined?(PokemonPokedexInfo_Scene) = #{defined?(PokemonPokedexInfo_Scene).inspect}")

if defined?(PokemonPokedexInfo_Scene)
  PokedexVoiceOver.log("  PokemonPokedexInfo_Scene exists — installing hooks")
  PokedexVoiceOver.log("  Instance methods: #{PokemonPokedexInfo_Scene.instance_methods(false).sort.inspect}")

  class PokemonPokedexInfo_Scene
    POKEDEX_VO_ENTRY_PAGE = 1   # page index that shows the Pokédex description (KIF uses 1-based pages)

    # Helper: read the current species + fusion partner from scene state.
    #
    # Searches multiple sources in order of reliability after navigation:
    #   1. @dummyPokemon (explicitly refreshed by pbUpdateDummyPokemon)
    #   2. @dexlist[@index] (index is updated first during scrolling)
    #   3. @species and other direct ivars (may be stale after pbGoToNext)
    #
    # Uses instance_variable_defined? instead of rescue — Ruby ivars return
    # nil silently, so rescue never triggers.
    def pokedex_vo_current_species
      head = nil
      fused = nil

      # --- Strategy 0: @dummyPokemon (most reliable after navigation) ---
      # KIF creates/updates @dummyPokemon via pbUpdateDummyPokemon for each
      # dex entry.  It is the freshest source after pbGoToNext/pbGoToPrevious.
      if instance_variable_defined?(:@dummyPokemon) && @dummyPokemon
        dummy = @dummyPokemon
        PokedexVoiceOver.log("  @dummyPokemon class=#{dummy.class}, methods=#{([:species, :fused, :fused_species, :fusion_partner, :fused_with, :getSpecies, :id_number, :speciesName] & dummy.methods).inspect}")

        # Extract head species
        if dummy.respond_to?(:species)
          val = dummy.species rescue nil
          if val && !(val.is_a?(Integer) && val <= 0)
            head = val
            PokedexVoiceOver.log("  Head species from @dummyPokemon.species: #{val.inspect}")
          end
        end

        # Extract fusion partner from @dummyPokemon
        if fused.nil?
          [:fused, :fused_species, :fusion_partner, :fused_with, :fusion_body].each do |attr|
            next unless dummy.respond_to?(attr)
            begin
              val = dummy.send(attr)
              next if val.nil?
              next if val.is_a?(Integer) && val <= 0
              if val.is_a?(Array) && val.length > 0
                fused = val[0]
                PokedexVoiceOver.log("  Fused species from @dummyPokemon.#{attr}[0]: #{fused.inspect}")
              else
                fused = val
                PokedexVoiceOver.log("  Fused species from @dummyPokemon.#{attr}: #{fused.inspect}")
              end
              break
            rescue StandardError => e
              PokedexVoiceOver.log("  @dummyPokemon.#{attr} failed: #{e.message}")
            end
          end
        end
      end

      # --- Strategy 1: @dexlist[@index] (index is always up-to-date) ---
      if head.nil? && instance_variable_defined?(:@dexlist) && instance_variable_defined?(:@index)
        begin
          entry = instance_variable_get(:@dexlist)[instance_variable_get(:@index)]
          if entry
            if entry.is_a?(Array)
              head = entry[0]
            elsif entry.respond_to?(:species)
              head = entry.species
            elsif entry.is_a?(Hash)
              head = entry[:species] || entry[:id]
            else
              head = entry
            end
            PokedexVoiceOver.log("  Head species found via @dexlist[@index]: #{head.inspect}")
          end
        rescue StandardError => e
          PokedexVoiceOver.log("  @dexlist[@index] lookup failed: #{e.message}")
        end
      end

      # --- Strategy 2: Direct ivar names (may be stale after navigation) ---
      if head.nil?
        [:@species, :@current_species, :@dexdata].each do |var|
          if instance_variable_defined?(var)
            val = instance_variable_get(var)
            next if val.nil?
            head = val
            PokedexVoiceOver.log("  Head species found in #{var}: #{val.inspect}")
            break
          end
        end
      end

      if head.nil?
        PokedexVoiceOver.log("  WARNING: Could not find head species")
        vars = instance_variables.select { |v| v.to_s =~ /species|dexlist|dexdata|fused|fusion|pokemon/i }
        vars.each do |v|
          PokedexVoiceOver.log("    #{v} = #{instance_variable_get(v).inspect rescue '<error>'}")
        end
        PokedexVoiceOver.log("  All scene ivars: #{instance_variables.sort.inspect}")
      end

      # --- Fusion decomposition from composite integer ID ---
      # KIF encodes fused Pokémon as: head_id * NB_POKEMON + body_id.
      # We try to obtain a numeric composite ID from multiple sources:
      #   1. head itself (if it's already an integer > NB_POKEMON)
      #   2. @dummyPokemon.id_number (when head is a Symbol but id_number
      #      holds the composite integer — common in newer KIF builds)
      if fused.nil?
        composite = nil
        if head.is_a?(Integer) && head > 0
          composite = head
        elsif instance_variable_defined?(:@dummyPokemon) && @dummyPokemon
          # head was a Symbol — try id_number for the composite integer
          dummy = @dummyPokemon
          if dummy.respond_to?(:id_number)
            begin
              val = dummy.id_number
              composite = val if val.is_a?(Integer) && val > 0
              PokedexVoiceOver.log("  Fusion decomposition: id_number=#{val.inspect} (head was #{head.class})")
            rescue StandardError => e
              PokedexVoiceOver.log("  @dummyPokemon.id_number failed: #{e.message}")
            end
          end
        end

        if composite
          nb_pokemon = PokedexVoiceOver.nb_pokemon

          if nb_pokemon && nb_pokemon > 0 && composite > nb_pokemon
            body_id = composite % nb_pokemon
            head_id = composite / nb_pokemon
            if head_id > 0 && body_id > 0
              PokedexVoiceOver.log("  Detected fused species ID #{composite} => head=#{head_id}, body=#{body_id} (NB_POKEMON=#{nb_pokemon})")
              fused = body_id
              head = head_id
            end
          end
        end
      end

      # --- Separate fused-species ivars (fallback) ---
      if fused.nil?
        [:@fusedSpecies, :@dexSpecies2, :@speciesFused, :@fused_species, :@species2].each do |var|
          if instance_variable_defined?(var)
            val = instance_variable_get(var)
            next if val.nil?
            next if val.is_a?(Integer) && val <= 0
            fused = val
            PokedexVoiceOver.log("  Fused species found in #{var}: #{val.inspect}")
            break
          end
        end
      end

      # Cross-check: log if @species differs from @dummyPokemon (stale-state detection)
      if head && instance_variable_defined?(:@species)
        ivar_sp = instance_variable_get(:@species)
        if ivar_sp && ivar_sp != head
          PokedexVoiceOver.log("  NOTE: @species=#{ivar_sp.inspect} differs from detected head=#{head.inspect} (stale ivar?)")
        end
      end

      PokedexVoiceOver.log("  pokedex_vo_current_species => head=#{head.inspect}, fused=#{fused.inspect}")
      [head, fused]
    end

    # Helper: try to read the currently displayed Pokédex entry text from
    # the scene state.  Used to match the correct audio variant instead of
    # picking one at random.
    #
    # Tries multiple strategies since KIF/PIF versions may store the text
    # in different places.  Returns nil if the text cannot be determined
    # (the caller should fall back to random variant selection).
    #
    # Strategy order (most reliable first):
    #   1. @dummyPokemon attributes (refreshed by pbUpdateDummyPokemon)
    #   2. KIF-specific scene methods (getCustomDexEntry, etc.)
    #   3. Instance variable scan (may be stale after navigation)
    #   4. GameData lookups
    #   5. pbGetMessage fallback
    def pokedex_vo_displayed_text
      text = nil

      # Strategy 1: @dummyPokemon (most reliable — refreshed each navigation)
      if text.nil? && instance_variable_defined?(:@dummyPokemon)
        dummy = @dummyPokemon
        if dummy
          [:pokedex_entry, :description, :real_description, :dex_entry,
           :real_pokedex_entry, :entry_text, :dexentry].each do |attr|
            next unless dummy.respond_to?(attr)
            begin
              val = dummy.send(attr)
              if val.is_a?(String) && val.strip.length > 10
                text = val
                PokedexVoiceOver.log("  Displayed text found via @dummyPokemon.#{attr}")
                break
              end
            rescue StandardError => e
              PokedexVoiceOver.log("  @dummyPokemon.#{attr} failed: #{e.message}")
            end
          end
        end
      end

      # Strategy 2: KIF-specific scene methods (use current internal state)
      # These methods require arguments (species ID or head/body pair).
      # We detect the current species first, then try each method with the
      # appropriate arguments, falling back to fewer args on ArgumentError.
      if text.nil?
        kif_head, kif_fused = pokedex_vo_current_species
        nb = PokedexVoiceOver.nb_pokemon
        kif_composite = nil
        if kif_head && kif_fused && nb && nb > 0 && kif_head.is_a?(Integer) && kif_fused.is_a?(Integer)
          kif_composite = kif_head * nb + kif_fused
        end

        # Helper to extract a usable string from a method return value
        extract_text = lambda do |val|
          if val.is_a?(String) && val.strip.length > 10
            val
          elsif val.is_a?(Array)
            val.find { |v| v.is_a?(String) && v.strip.length > 10 }
          else
            nil
          end
        end

        # Try each method with progressively fewer arguments until one works
        [:getCustomDexEntry, :getCustomEntryText, :getAIDexEntry].each do |method_name|
          next unless respond_to?(method_name, true)
          val = nil
          called_with = nil

          # Build a list of argument sets to try (most specific first)
          arg_sets = []
          if method_name == :getAIDexEntry
            # getAIDexEntry expects (head, body) for fusions
            arg_sets << [kif_head, kif_fused] if kif_head && kif_fused
            arg_sets << [kif_composite] if kif_composite
            arg_sets << [kif_head] if kif_head
          else
            # getCustomDexEntry / getCustomEntryText expect (species)
            arg_sets << [kif_composite] if kif_composite
            arg_sets << [kif_head] if kif_head
          end
          # Always try with zero args as a last resort
          arg_sets << []

          arg_sets.each do |args|
            begin
              val = send(method_name, *args)
              called_with = args
              break
            rescue ArgumentError => e
              PokedexVoiceOver.log("  #{method_name}(#{args.map(&:inspect).join(', ')}) arg error: #{e.message}")
              val = nil
            rescue StandardError => e
              PokedexVoiceOver.log("  #{method_name}(#{args.map(&:inspect).join(', ')}) failed: #{e.message}")
              val = nil
              break  # non-argument errors are unlikely to be fixed by fewer args
            end
          end

          result = extract_text.call(val)
          if result
            text = result
            PokedexVoiceOver.log("  Displayed text found via #{method_name}(#{called_with&.map(&:inspect)&.join(', ')})")
            break
          end
        end
      end

      # Strategy 3: Check common instance variable names for entry text
      if text.nil?
        [:@dexEntry, :@entryText, :@description, :@pokemonEntry,
         :@dex_entry, :@entry_text, :@fusionEntry, :@fusion_entry,
         :@desc, :@dexentry, :@entrytext, :@pokedex_entry,
         :@entry, :@dex_text, :@pokemon_entry].each do |var|
          if instance_variable_defined?(var)
            val = instance_variable_get(var)
            if val.is_a?(String) && val.strip.length > 10
              text = val
              PokedexVoiceOver.log("  Displayed text found in #{var}")
              break
            end
          end
        end
      end

      # Strategy 4: Check @sprites hash for text overlay windows
      # KIF stores Pokédex text in sprite overlay windows; the displayed entry
      # text is often in a Window with a .text property.
      if text.nil? && instance_variable_defined?(:@sprites) && @sprites.is_a?(Hash)
        @sprites.each do |key, sprite|
          next unless sprite
          # Try .text property (common for Window_UnformattedTextPokemon etc.)
          [:text, :getText].each do |text_method|
            next unless sprite.respond_to?(text_method)
            begin
              val = sprite.send(text_method)
              if val.is_a?(String) && val.strip.length > 10
                text = val
                PokedexVoiceOver.log("  Displayed text found in @sprites[#{key.inspect}].#{text_method}")
                break
              end
            rescue StandardError
              next
            end
          end
          break if text
        end
      end

      # Strategy 5: Try GameData for both regular and fused species
      # For fusions, cross-check the composite result against the head
      # species' base entry text — if they match, the composite lookup
      # returned stale/wrong data (the head species text, not the fusion's).
      if text.nil? && defined?(GameData::Species)
        head, fused = pokedex_vo_current_species

        # Pre-fetch head species' base text for cross-checking fusions
        head_base_text = nil
        if head && fused
          begin
            head_data = GameData::Species.get(head)
            if head_data.respond_to?(:real_description)
              head_base_text = head_data.real_description
            elsif head_data.respond_to?(:pokedex_entry)
              head_base_text = head_data.pokedex_entry
            end
          rescue StandardError
            # ignore — head_base_text remains nil
          end
        end

        # For fusions, try the composite species ID first — KIF registers
        # fusion entries under the composite key in GameData::Species.
        if head && fused
          nb = PokedexVoiceOver.nb_pokemon
          composite = nil
          if nb && nb > 0 && head.is_a?(Integer) && fused.is_a?(Integer)
            composite = head * nb + fused
          end
          if composite
            begin
              data = GameData::Species.get(composite)
              candidate = nil
              if data.respond_to?(:pokedex_entry)
                val = data.pokedex_entry
                candidate = val if val.is_a?(String) && val.strip.length > 10
              end
              if candidate.nil? && data.respond_to?(:real_description)
                val = data.real_description
                candidate = val if val.is_a?(String) && val.strip.length > 10
              end
              # Discard if the composite text is identical to the head
              # species' base entry — this means GameData returned the
              # base species' text rather than the fusion's custom entry.
              if candidate && head_base_text
                norm_candidate = PokedexVoiceOver._normalize_text(candidate)
                norm_head = PokedexVoiceOver._normalize_text(head_base_text)
                if norm_candidate == norm_head
                  PokedexVoiceOver.log("  GameData composite #{composite} text matches head species base entry — discarding as stale")
                  candidate = nil
                end
              end
              if candidate
                text = candidate
                PokedexVoiceOver.log("  Displayed text found via GameData (composite #{composite})")
              end
            rescue StandardError => e
              PokedexVoiceOver.log("  GameData composite lookup failed: #{e.message}")
            end
          end
        end

        # For regular species, or if fusion composite lookup failed
        if text.nil? && head
          begin
            data = GameData::Species.get(head)
            if data.respond_to?(:real_description)
              text = data.real_description
            elsif data.respond_to?(:pokedex_entry)
              text = data.pokedex_entry
            end
            PokedexVoiceOver.log("  Displayed text found via GameData") if text
          rescue StandardError => e
            PokedexVoiceOver.log("  GameData text lookup failed: #{e.message}")
          end
        end
      end

      # Strategy 6: Try pbGetMessage for both regular and fused species
      if text.nil?
        head, fused = pokedex_vo_current_species
        if defined?(MessageTypes) && defined?(MessageTypes::Entries)
          begin
            # For fusions, try the composite ID first
            if head && fused
              nb = PokedexVoiceOver.nb_pokemon
              if nb && nb > 0 && head.is_a?(Integer) && fused.is_a?(Integer)
                composite = head * nb + fused
                val = pbGetMessage(MessageTypes::Entries, composite) rescue nil
                if val.is_a?(String) && !val.strip.empty? && val.strip.length > 10
                  text = val
                  PokedexVoiceOver.log("  Displayed text found via pbGetMessage (composite #{composite})")
                end
              end
            end
            # For regular species, or if fusion pbGetMessage failed
            if text.nil? && head
              sp_data = GameData::Species.get(head) if defined?(GameData::Species)
              id_num = sp_data.id_number if sp_data && sp_data.respond_to?(:id_number)
              if id_num
                text = pbGetMessage(MessageTypes::Entries, id_num) rescue nil
                PokedexVoiceOver.log("  Displayed text found via pbGetMessage") if text && !text.empty?
                text = nil if text && text.empty?
              end
            end
          rescue StandardError => e
            PokedexVoiceOver.log("  pbGetMessage text lookup failed: #{e.message}")
          end
        end
      end

      # Log all long string ivars for debugging (helps identify where KIF stores fusion text)
      if text.nil?
        PokedexVoiceOver.log("  Could not find displayed text — logging string ivars for debugging:")
        instance_variables.sort.each do |var|
          next if var.to_s.start_with?("@dex_vo_")
          val = instance_variable_get(var) rescue next
          if val.is_a?(String) && val.strip.length > 20
            PokedexVoiceOver.log("    #{var} (#{val.length} chars): #{val[0, 80].inspect}")
          end
        end
      end

      text
    end

    # ------------------------------------------------------------------
    # pbStartScene  — play when the Pokédex entry scene first opens
    # ------------------------------------------------------------------
    if method_defined?(:pbStartScene)
      PokedexVoiceOver.log("  Aliasing pbStartScene")
      alias dex_vo_orig_pbStartScene pbStartScene

      def pbStartScene(*args)
        dex_vo_orig_pbStartScene(*args)

        # NOTE: @page is nil (not an error) if the original method hasn't
        # set it yet.  In Ruby, accessing an undefined ivar returns nil —
        # it does NOT raise, so `rescue` never triggers.  We treat nil as
        # "we're on the entry page" because pbStartScene always opens to
        # the default page.
        page = @page
        PokedexVoiceOver.log("pbStartScene fired — @page=#{page.inspect}, entry_page=#{POKEDEX_VO_ENTRY_PAGE}")

        if page.nil? || page == POKEDEX_VO_ENTRY_PAGE
          head, fused = pokedex_vo_current_species
          @dex_vo_last_species = [head, fused]
          text = pokedex_vo_displayed_text
          PokedexVoiceOver.play(head, fused, text)
          # Signal to drawPage that we already played for this species,
          # preventing double-play when drawPage fires right after us.
          @dex_vo_scene_played = true
        else
          PokedexVoiceOver.log("  Skipping — page #{page} is not the entry page (#{POKEDEX_VO_ENTRY_PAGE})")
          PokedexVoiceOver.log("  Hint: if the voice should play here, set POKEDEX_VO_ENTRY_PAGE = #{page}")
        end
      end
    else
      PokedexVoiceOver.log("  WARNING: pbStartScene is NOT defined — cannot hook scene open")
    end

    # ------------------------------------------------------------------
    # pbShowPage  — play (optionally) when returning to the entry page
    # ------------------------------------------------------------------
    if method_defined?(:pbShowPage)
      PokedexVoiceOver.log("  Aliasing pbShowPage")
      alias dex_vo_orig_pbShowPage pbShowPage

      def pbShowPage(page, *args)
        prev_page = @page  # nil if not yet set (see note in pbStartScene)
        dex_vo_orig_pbShowPage(page, *args)

        PokedexVoiceOver.log("pbShowPage fired — page=#{page.inspect}, prev=#{prev_page.inspect}, play_on_change=#{PokedexVoiceOver.play_on_page_change?}")

        if page == POKEDEX_VO_ENTRY_PAGE
          head, fused = pokedex_vo_current_species
          current_species = [head, fused]
          species_changed = current_species != @dex_vo_last_species
          page_changed = prev_page != POKEDEX_VO_ENTRY_PAGE

          # Check and clear the navigation/scene played flags to prevent
          # double-play when pbGoToNext/pbGoToPrevious or pbStartScene
          # already played for this species.
          if @dex_vo_nav_played || @dex_vo_scene_played
            PokedexVoiceOver.log("  pbShowPage: skipping — already played by #{@dex_vo_nav_played ? 'navigation' : 'pbStartScene'} hook")
            @dex_vo_last_species = current_species
            @dex_vo_nav_played = false
            @dex_vo_scene_played = false
          elsif species_changed
            PokedexVoiceOver.log("  pbShowPage: species changed — playing")
            @dex_vo_last_species = current_species
            text = pokedex_vo_displayed_text
            PokedexVoiceOver.play(head, fused, text)
          elsif page_changed && PokedexVoiceOver.play_on_page_change?
            text = pokedex_vo_displayed_text
            PokedexVoiceOver.play(head, fused, text)
          end
        end
      end
    else
      PokedexVoiceOver.log("  pbShowPage is NOT defined — trying drawPage as fallback")

      # KIF uses drawPage instead of pbShowPage for page rendering.
      # Hook it so the "play_on_page_change" feature still works.
      if method_defined?(:drawPage)
        PokedexVoiceOver.log("  Aliasing drawPage (fallback for pbShowPage)")
        alias dex_vo_orig_drawPage drawPage

        def drawPage(page, *args)
          prev_page = @page  # capture before the original method updates it
          dex_vo_orig_drawPage(page, *args)

          PokedexVoiceOver.log("drawPage fired — page=#{page.inspect}, prev=#{prev_page.inspect}, play_on_change=#{PokedexVoiceOver.play_on_page_change?}")

          if page == POKEDEX_VO_ENTRY_PAGE
            head, fused = pokedex_vo_current_species
            current_species = [head, fused]
            species_changed = current_species != @dex_vo_last_species
            page_changed = prev_page != POKEDEX_VO_ENTRY_PAGE

            # Check and clear the navigation/scene played flags to prevent
            # double-play when pbGoToNext/pbGoToPrevious or pbStartScene
            # already played for this species.
            if @dex_vo_nav_played || @dex_vo_scene_played
              PokedexVoiceOver.log("  drawPage: skipping — already played by #{@dex_vo_nav_played ? 'navigation' : 'pbStartScene'} hook")
              @dex_vo_last_species = current_species
              @dex_vo_nav_played = false
              @dex_vo_scene_played = false
            elsif species_changed
              PokedexVoiceOver.log("  drawPage: species changed (#{@dex_vo_last_species.inspect} -> #{current_species.inspect}) — playing")
              @dex_vo_last_species = current_species
              text = pokedex_vo_displayed_text
              PokedexVoiceOver.play(head, fused, text)
            elsif page_changed && PokedexVoiceOver.play_on_page_change?
              PokedexVoiceOver.log("  drawPage: page changed to entry page — replaying")
              text = pokedex_vo_displayed_text
              PokedexVoiceOver.play(head, fused, text)
            end
          end
        end
      else
        PokedexVoiceOver.log("  WARNING: Neither pbShowPage nor drawPage defined — cannot hook page changes")
      end
    end

    # ------------------------------------------------------------------
    # pbEndScene  — stop the voice when the scene closes
    # ------------------------------------------------------------------
    if method_defined?(:pbEndScene)
      PokedexVoiceOver.log("  Aliasing pbEndScene")
      alias dex_vo_orig_pbEndScene pbEndScene

      def pbEndScene(*args)
        PokedexVoiceOver.log("pbEndScene fired")
        PokedexVoiceOver.stop
        dex_vo_orig_pbEndScene(*args)
      end
    else
      PokedexVoiceOver.log("  WARNING: pbEndScene is NOT defined — cannot hook scene close")
    end

    # ------------------------------------------------------------------
    # pbGoToNext / pbGoToPrevious — play voice when scrolling between
    # Pokémon entries in the Pokédex info scene
    # ------------------------------------------------------------------
    if method_defined?(:pbGoToNext)
      PokedexVoiceOver.log("  Aliasing pbGoToNext")
      alias dex_vo_orig_pbGoToNext pbGoToNext

      def pbGoToNext(*args)
        prev_species = @dex_vo_last_species
        dex_vo_orig_pbGoToNext(*args)

        PokedexVoiceOver.log("pbGoToNext fired — @page=#{@page.inspect}, prev_species=#{prev_species.inspect}")

        head, fused = pokedex_vo_current_species
        @dex_vo_last_species = [head, fused]
        if head == prev_species&.first && fused == prev_species&.last
          PokedexVoiceOver.log("  WARNING: species unchanged after pbGoToNext — possible stale state")
        end
        text = pokedex_vo_displayed_text
        PokedexVoiceOver.play(head, fused, text)
        # Signal to drawPage/pbShowPage that we already played for this
        # species, preventing the double-play that occurs when the page
        # rendering hook fires immediately after navigation.
        @dex_vo_nav_played = true
      end
    else
      PokedexVoiceOver.log("  WARNING: pbGoToNext is NOT defined — cannot hook next-entry navigation")
    end

    if method_defined?(:pbGoToPrevious)
      PokedexVoiceOver.log("  Aliasing pbGoToPrevious")
      alias dex_vo_orig_pbGoToPrevious pbGoToPrevious

      def pbGoToPrevious(*args)
        prev_species = @dex_vo_last_species
        dex_vo_orig_pbGoToPrevious(*args)

        PokedexVoiceOver.log("pbGoToPrevious fired — @page=#{@page.inspect}, prev_species=#{prev_species.inspect}")

        head, fused = pokedex_vo_current_species
        @dex_vo_last_species = [head, fused]
        if head == prev_species&.first && fused == prev_species&.last
          PokedexVoiceOver.log("  WARNING: species unchanged after pbGoToPrevious — possible stale state")
        end
        text = pokedex_vo_displayed_text
        PokedexVoiceOver.play(head, fused, text)
        # Signal to drawPage/pbShowPage that we already played for this
        # species, preventing the double-play that occurs when the page
        # rendering hook fires immediately after navigation.
        @dex_vo_nav_played = true
      end
    else
      PokedexVoiceOver.log("  WARNING: pbGoToPrevious is NOT defined — cannot hook previous-entry navigation")
    end
  end

  PokedexVoiceOver.log("Hook installation complete")
else
  PokedexVoiceOver.log("ERROR: PokemonPokedexInfo_Scene is NOT defined!")
  PokedexVoiceOver.log("  The mod cannot hook into the Pokédex scene.")
  PokedexVoiceOver.log("  This usually means the mod loaded BEFORE the game's Pokédex scripts.")
  # Try to discover any Pokédex-related classes so we can suggest the right name
  begin
    pokedex_classes = ObjectSpace.each_object(Class).select do |c|
      c.name.to_s =~ /pokedex|dex.*info|dex.*scene/i rescue false
    end
    if pokedex_classes.any?
      PokedexVoiceOver.log("  Pokédex-related classes found: #{pokedex_classes.map(&:name).sort.inspect}")
    else
      PokedexVoiceOver.log("  No Pokédex-related classes found — the class may load later")
    end
  rescue StandardError => e
    PokedexVoiceOver.log("  ObjectSpace scan failed: #{e.message}")
  end
end

# =============================================================================
# Hook into PokemonPokedex_Scene (the Pokédex list / menu)
# =============================================================================
# Mute BGM as soon as the player opens the Pokédex menu (not just when viewing
# an individual entry) and restore it when the menu is closed completely.

PokedexVoiceOver.log("  defined?(PokemonPokedex_Scene) = #{defined?(PokemonPokedex_Scene).inspect}")

if defined?(PokemonPokedex_Scene)
  PokedexVoiceOver.log("  PokemonPokedex_Scene exists — installing BGM hooks")

  class PokemonPokedex_Scene
    if method_defined?(:pbStartScene)
      PokedexVoiceOver.log("  Aliasing PokemonPokedex_Scene#pbStartScene")
      alias dex_vo_orig_list_pbStartScene pbStartScene

      def pbStartScene(*args)
        dex_vo_orig_list_pbStartScene(*args)
        PokedexVoiceOver.log("PokemonPokedex_Scene#pbStartScene fired — muting BGM")
        PokedexVoiceOver.save_and_mute_bgm
      end
    else
      PokedexVoiceOver.log("  WARNING: PokemonPokedex_Scene#pbStartScene is NOT defined")
    end

    if method_defined?(:pbEndScene)
      PokedexVoiceOver.log("  Aliasing PokemonPokedex_Scene#pbEndScene")
      alias dex_vo_orig_list_pbEndScene pbEndScene

      def pbEndScene(*args)
        PokedexVoiceOver.log("PokemonPokedex_Scene#pbEndScene fired — restoring BGM")
        PokedexVoiceOver.stop
        PokedexVoiceOver.restore_bgm
        dex_vo_orig_list_pbEndScene(*args)
      end
    else
      PokedexVoiceOver.log("  WARNING: PokemonPokedex_Scene#pbEndScene is NOT defined")
    end
  end

  PokedexVoiceOver.log("  PokemonPokedex_Scene BGM hooks installed")
else
  PokedexVoiceOver.log("  WARNING: PokemonPokedex_Scene is NOT defined — BGM will be muted/restored per-entry instead")

  # Fallback: if the list scene class doesn't exist, keep BGM management in
  # PokemonPokedexInfo_Scene so the feature still works (just scoped to entries).
  if defined?(PokemonPokedexInfo_Scene)
    class PokemonPokedexInfo_Scene
      if method_defined?(:dex_vo_orig_pbStartScene) && !method_defined?(:dex_vo_fallback_bgm_start)
        alias dex_vo_fallback_bgm_start pbStartScene

        def pbStartScene(*args)
          PokedexVoiceOver.save_and_mute_bgm
          dex_vo_fallback_bgm_start(*args)
        end
      end

      if method_defined?(:dex_vo_orig_pbEndScene) && !method_defined?(:dex_vo_fallback_bgm_end)
        alias dex_vo_fallback_bgm_end pbEndScene

        def pbEndScene(*args)
          PokedexVoiceOver.restore_bgm
          dex_vo_fallback_bgm_end(*args)
        end
      end
    end
    PokedexVoiceOver.log("  Fallback: BGM hooks added to PokemonPokedexInfo_Scene")
  end
end

PokedexVoiceOver.log("Mod loading finished")
PokedexVoiceOver.log("=" * 60)

# =============================================================================
# Mod Settings submenu scene (Stonewall's Mod Settings mod)
# =============================================================================
# Creates a dedicated Pokédex Voice Over settings submenu that opens when the
# user clicks the "Pokédex Voice Over" entry under the Interface category.
#
# Follows the same submenu pattern used by the Economy Mod and other KIF mods.
# See: https://github.com/Stonewallx/KIF-Mods/blob/main/Documentation/Mod%20Settings.md

class PokedexVoiceOverSettingsScene < PokemonOption_Scene
  include ModSettingsSpacing if defined?(ModSettingsSpacing)

  # Skip fade-in to avoid double-fade (outer pbFadeOutIn handles the transition)
  def pbFadeInAndShow(sprites, visiblesprites = nil)
    if visiblesprites
      visiblesprites.each { |s| sprites[s].visible = true }
    else
      sprites.each { |key, sprite| sprite.visible = true if sprite }
    end
  end

  def pbGetOptions(inloadscreen = false)
    options = []

    options << EnumOption.new(
      _INTL("Enable Voice Over"),
      [_INTL("Off"), _INTL("On")],
      proc { ModSettingsMenu.get(:pokedex_vo_enabled) || 0 },
      proc { |value| ModSettingsMenu.set(:pokedex_vo_enabled, value) },
      _INTL("Enable or disable Pokédex voice-over narration")
    )

    options << StoneSliderOption.new(
      _INTL("Voice Volume"),
      0, 100, 5,
      proc { ModSettingsMenu.get(:pokedex_vo_volume) || 80 },
      proc { |value| ModSettingsMenu.set(:pokedex_vo_volume, value) },
      _INTL("Adjust the volume of the Pokédex voice-over narration")
    )

    options << EnumOption.new(
      _INTL("Mute Music in Pokédex"),
      [_INTL("Off"), _INTL("On")],
      proc { ModSettingsMenu.get(:pokedex_vo_mute_music) || 0 },
      proc { |value| ModSettingsMenu.set(:pokedex_vo_mute_music, value) },
      _INTL("Mute background music while the Pokédex is open")
    )

    options << EnumOption.new(
      _INTL("Re-read on Page Return"),
      [_INTL("Off"), _INTL("On")],
      proc { ModSettingsMenu.get(:pokedex_vo_replay_on_page_change) || 0 },
      proc { |value| ModSettingsMenu.set(:pokedex_vo_replay_on_page_change, value) },
      _INTL("Replay the voice-over when navigating back to the description page")
    )

    options = auto_insert_spacers(options) if defined?(ModSettingsSpacing) && respond_to?(:auto_insert_spacers)
    return options
  end

  def pbStartScene(inloadscreen = false)
    super

    # Set custom title
    @sprites["title"] = Window_UnformattedTextPokemon.newWithSize(
      _INTL("Pokédex Voice Over"), 0, 0, Graphics.width, 64, @viewport)

    # Apply current color theme and modsettings_menu flag
    if @sprites["option"]
      @sprites["option"].modsettings_menu = true if @sprites["option"].respond_to?(:modsettings_menu=)

      if defined?(ModSettingsMenu) && defined?(COLOR_THEMES)
        theme_index = ModSettingsMenu.get(:modsettings_color_theme) || 0
        theme_key = COLOR_THEMES.keys[theme_index]
        if theme_key
          theme = COLOR_THEMES[theme_key]
          if theme[:base] && theme[:shadow]
            @sprites["option"].nameBaseColor = theme[:base]
            @sprites["option"].nameShadowColor = theme[:shadow]
            @sprites["option"].selBaseColor = theme[:base]
            @sprites["option"].selShadowColor = theme[:shadow]
          end
        end
      end
    end

    # Initialize values
    for i in 0...@PokemonOptions.length
      @sprites["option"][i] = (@PokemonOptions[i].get || 0)
    end
    @sprites["option"].refresh

    pbFadeInAndShow(@sprites) { pbUpdate }
  end
end

# =============================================================================
# Mod Settings menu registration
# =============================================================================
# Registers a single "Pokédex Voice Over" button under the Interface category
# that opens the dedicated submenu scene above.
#
# When the Mod Settings system has already loaded, we register immediately.
# Otherwise we queue the registrations via $MOD_SETTINGS_PENDING_REGISTRATIONS
# so they are picked up once the Mod Settings system initialises later.

pokedex_vo_register_settings = proc {
  # Ensure default values are initialised in storage
  ModSettingsMenu.set(:pokedex_vo_enabled, 1) if ModSettingsMenu.get(:pokedex_vo_enabled).nil?
  ModSettingsMenu.set(:pokedex_vo_volume, 80) if ModSettingsMenu.get(:pokedex_vo_volume).nil?
  ModSettingsMenu.set(:pokedex_vo_mute_music, 1) if ModSettingsMenu.get(:pokedex_vo_mute_music).nil?
  ModSettingsMenu.set(:pokedex_vo_replay_on_page_change, 0) if ModSettingsMenu.get(:pokedex_vo_replay_on_page_change).nil?

  ModSettingsMenu.register(:pokedex_vo_submenu, {
    name: "Pokédex Voice Over",
    type: :button,
    description: "Configure Pokédex voice-over settings",
    on_press: proc {
      pbFadeOutIn {
        scene = PokedexVoiceOverSettingsScene.new
        screen = PokemonOptionScreen.new(scene)
        screen.pbStartScreen
      }
    },
    category: "Interface",
    searchable: [
      "voice over", "pokedex", "volume", "mute music", "narration",
      "dexter", "voice", "audio", "re-read", "page change"
    ]
  })
}

if defined?(ModSettingsMenu)
  # Mod Settings system is already available — register immediately.
  pokedex_vo_register_settings.call
else
  # Mod Settings system hasn't loaded yet — queue for later processing.
  $MOD_SETTINGS_PENDING_REGISTRATIONS ||= []
  $MOD_SETTINGS_PENDING_REGISTRATIONS << pokedex_vo_register_settings
end
