#!/usr/bin/env python3
"""
Pokédex Voice-Over Generator for KIF (Kuray's Infinite Fusion)
==============================================================

Generates TTS audio files for every Pokédex entry in your KIF game,
voiced in the style of Dexter — the classic Pokémon anime Pokédex narrator.

The script reads Pokédex description text from the game's PBS data files,
synthesises speech, and exports OGG Vorbis audio files.

Data sources (checked in order):
  1. Data/species.dat     (KIF compiled species database — requires rubymarshal)
  2. PBS/pokemon.txt      (vanilla PIF plain-text PBS)
  3. Data/Scripts/990_NPT/001_Registration.rb (and similar Ruby scripts that
     use GameData::Species.register({...}) blocks — supplementary species)
  4. --pbs-file / --registration-file explicit overrides

TTS backends
------------
  --backend fakeyou   (RECOMMENDED) Uses the FakeYou AI voice model
                      "Pokedex (Pokemon, 4Kids)" — a community-trained model
                      that replicates the real Dexter voice from the anime.
                      Same approach used by github.com/adriantwarog/Pokedex-RL.
                      Requires internet access.

  --backend pyttsx3   Offline fallback — uses OS built-in voices (SAPI on
                      Windows, NSSpeechSynthesizer on macOS, eSpeak on Linux)
                      with post-processing effects.

  --backend gtts      Online fallback — uses Google's Text-to-Speech API
                      with post-processing effects.

Output files are saved as OGG Vorbis to:
  <game-dir>/Audio/SE/Pokedex/

A duration manifest is written alongside the audio files:
  <game-dir>/Audio/SE/Pokedex/dex_durations.json

Naming convention
-----------------
  dex_BULBASAUR.ogg               — regular Pokémon
  dex_BULBASAUR_CHARMANDER.ogg    — fused Pokémon (head_body)

Usage
-----
  # RECOMMENDED — Generate using the real anime Pokédex voice via FakeYou
  python generate_voices.py --game-dir /path/to/KIF --backend fakeyou

  # With FakeYou priority queue access (faster generation)
  python generate_voices.py --game-dir /path/to/KIF --backend fakeyou --fakeyou-cookie YOUR_COOKIE

  # Generate all regular Pokémon entries (creates files, skips existing ones)
  python generate_voices.py --game-dir /path/to/KIF

  # Overwrite any previously generated files
  python generate_voices.py --game-dir /path/to/KIF --overwrite

  # Retry only entries that failed in a previous run
  python generate_voices.py --game-dir /path/to/KIF --retry-failed

  # Generate for a single species only
  python generate_voices.py --game-dir /path/to/KIF --species BULBASAUR

  # Also generate fusion-specific entries (if your KIF build has them)
  # Fusions are now generated by default — use --no-fusions to skip
  python generate_voices.py --game-dir /path/to/KIF --no-fusions

  # With FakeYou login (auto-obtains session cookie)
  python generate_voices.py --game-dir /path/to/KIF --backend fakeyou --fakeyou-username YOU --fakeyou-password PASS

  # Use Google TTS instead of the default offline pyttsx3 backend
  python generate_voices.py --game-dir /path/to/KIF --backend gtts

  # Explicitly point to a PBS file (for non-standard installations)
  python generate_voices.py --game-dir /path/to/KIF --pbs-file /path/to/pokemon.txt

  # List available pyttsx3 voices and exit (useful for --voice selection)
  python generate_voices.py --list-voices

Requirements
------------
  pip install -r requirements.txt

  For --backend fakeyou:  requires the 'requests' package and internet access.

  For --backend pyttsx3:  On Windows, uses the built-in SAPI voices (e.g.
  "Microsoft David Desktop").  On macOS, it uses "Alex" or similar.  On
  Linux, it uses eSpeak.

  ffmpeg must be installed and on your PATH for pydub to export OGG files.
"""

import argparse
import json
import logging
import os
import re
import shutil
import sys
import tempfile
import time
import urllib.parse
import uuid
import warnings
from pathlib import Path

# ---------------------------------------------------------------------------
# Optional dependency detection
# ---------------------------------------------------------------------------

try:
    import pyttsx3
    HAS_PYTTSX3 = True
except ImportError:
    HAS_PYTTSX3 = False

try:
    from gtts import gTTS
    HAS_GTTS = True
except ImportError:
    HAS_GTTS = False

try:
    import requests as _requests
    HAS_REQUESTS = True
except ImportError:
    HAS_REQUESTS = False

try:
    # Suppress pydub's own RuntimeWarning about ffmpeg not being found at
    # import time — we perform our own explicit check below (HAS_FFMPEG).
    with warnings.catch_warnings():
        warnings.simplefilter("ignore", RuntimeWarning)
        from pydub import AudioSegment
        from pydub.effects import normalize
    HAS_PYDUB = True
except ImportError:
    HAS_PYDUB = False

# pydub requires ffmpeg (or avconv) to be on PATH for audio format conversion.
# Check once here so we can warn the user upfront instead of erroring per file.
HAS_FFMPEG = HAS_PYDUB and bool(shutil.which("ffmpeg") or shutil.which("avconv"))

try:
    from rubymarshal.reader import load as _rubymarshal_load
    from rubymarshal.classes import RubyObject as RubyObject
    HAS_RUBYMARSHAL = True
except ImportError:
    HAS_RUBYMARSHAL = False

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------

logging.basicConfig(
    level=logging.INFO,
    format="%(levelname)s: %(message)s",
)
log = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# PBS parsing
# ---------------------------------------------------------------------------

# Pokemon Essentials PBS pokemon.txt comes in two flavours:
#   Old (v18/v19 — used by vanilla PIF):  sections start with a numeric [001]
#   New (v20+):                            sections start with [INTERNAL_NAME]
# Both store the description in a  PokedexEntry=  key.

_PBS_SECTION_RE = re.compile(r"^\[(\w+)\]", re.MULTILINE)
_INTERNAL_NAME_RE = re.compile(r"^InternalName\s*=\s*(.+)$", re.MULTILINE)
_DEX_ENTRY_RE = re.compile(
    r"^PokedexEntry\s*=\s*(.+?)(?=\n\w|\Z)", re.MULTILINE | re.DOTALL
)


def _clean_entry_text(raw: str) -> str:
    """Normalise a raw Pokédex entry string for TTS consumption.

    We intentionally keep punctuation and double-spaces intact so that
    the entry-map text is as close as possible to what KIF displays at
    runtime.  The mod's ``_normalize_text`` in main.rb strips punctuation
    and collapses whitespace aggressively before comparison, so minor
    formatting differences no longer cause matching failures.
    """
    # Replace escaped newlines with a space
    text = raw.replace("\\n", " ")
    # Remove any remaining backslash escapes
    text = re.sub(r"\\.", " ", text)
    # Collapse runs of 3+ whitespace characters to double-space (preserve
    # the double-spaces that KIF's text engine commonly produces), then
    # strip leading/trailing whitespace.
    text = re.sub(r"[ \t]{3,}", "  ", text)
    text = text.strip()
    return text


def parse_pbs_pokemon(pbs_file: Path) -> dict:
    """
    Return a {SPECIES_NAME: entry_text} dict parsed from a PBS pokemon.txt.
    """
    entries: dict = {}

    if not pbs_file.is_file():
        log.warning("PBS file not found: %s", pbs_file)
        return entries

    try:
        content = pbs_file.read_text(encoding="utf-8", errors="replace")
    except OSError as exc:
        log.error("Cannot read %s: %s", pbs_file, exc)
        return entries

    # Split into per-Pokémon sections
    section_starts = [m.start() for m in _PBS_SECTION_RE.finditer(content)]
    for i, start in enumerate(section_starts):
        end = section_starts[i + 1] if i + 1 < len(section_starts) else len(content)
        section = content[start:end]

        # Determine the internal (species) name.
        # New-style PBS: the section header itself IS the internal name.
        header_match = _PBS_SECTION_RE.match(section)
        if not header_match:
            continue
        header_val = header_match.group(1)

        # Old-style PBS uses numeric section IDs, so we need InternalName=
        if header_val.isdigit():
            name_match = _INTERNAL_NAME_RE.search(section)
            if not name_match:
                continue
            species_name = name_match.group(1).strip().upper()
        else:
            species_name = header_val.upper()

        # Extract the Pokédex entry text
        entry_match = _DEX_ENTRY_RE.search(section)
        if not entry_match:
            continue

        raw_text = entry_match.group(1)
        entry_text = _clean_entry_text(raw_text)
        if entry_text:
            entries[species_name] = entry_text

    log.info("Parsed %d Pokédex entries from %s", len(entries), pbs_file.name)
    return entries


def parse_fusion_entries(game_dir: Path) -> dict:
    """
    Return a {(SPECIES1, SPECIES2): entry_text} dict from KIF fusion PBS data.

    KIF may store custom fusion Pokédex entries in various files; we attempt
    every known location.  Returns an empty dict if none are found.
    """
    fusion_entries: dict = {}

    candidate_files = [
        game_dir / "PBS" / "fusions.txt",
        game_dir / "PBS" / "fusion_dex.txt",
        game_dir / "PBS" / "fusionmon.txt",
    ]

    for path in candidate_files:
        if not path.is_file():
            continue
        log.info("Parsing fusion entries from %s", path)
        try:
            content = path.read_text(encoding="utf-8", errors="replace")
        except OSError as exc:
            log.warning("Cannot read %s: %s", path, exc)
            continue

        # Expected section format:
        #   [HEAD_BODY]
        #   PokedexEntry=...
        section_starts = [m.start() for m in _PBS_SECTION_RE.finditer(content)]
        for i, start in enumerate(section_starts):
            end = section_starts[i + 1] if i + 1 < len(section_starts) else len(content)
            section = content[start:end]

            header_match = _PBS_SECTION_RE.match(section)
            if not header_match:
                continue
            header_val = header_match.group(1).upper()

            # Expect a HEAD_BODY pair
            if "_" not in header_val:
                continue
            parts = header_val.split("_", 1)
            species1, species2 = parts[0], parts[1]

            entry_match = _DEX_ENTRY_RE.search(section)
            if not entry_match:
                continue
            raw_text = entry_match.group(1)
            entry_text = _clean_entry_text(raw_text)
            if entry_text:
                fusion_entries[(species1, species2)] = entry_text

    return fusion_entries


# ---------------------------------------------------------------------------
# KIF Data/ parsing (species.dat + JSON Pokédex files)
# ---------------------------------------------------------------------------

def _ruby_symbol_str(sym) -> str:
    """Convert a rubymarshal Symbol to a plain uppercase string."""
    if hasattr(sym, "name"):
        return sym.name.upper()
    return str(sym).lstrip(":").upper()


def _ruby_bytes_str(val) -> str:
    """Decode a rubymarshal bytes/string value to a Python str."""
    if isinstance(val, bytes):
        return val.decode("utf-8", errors="replace")
    return str(val) if val else ""


def parse_species_dat(species_dat: Path) -> dict:
    """
    Parse a KIF/Essentials ``Data/species.dat`` file and return a
    ``{SPECIES_NAME: entry_text}`` dict.

    Requires the ``rubymarshal`` package (``pip install rubymarshal``).
    Returns an empty dict if the file cannot be read or rubymarshal is not
    installed.
    """
    entries: dict = {}

    if not HAS_RUBYMARSHAL:
        log.debug("rubymarshal not installed — cannot parse species.dat")
        return entries

    if not species_dat.is_file():
        log.debug("species.dat not found: %s", species_dat)
        return entries

    try:
        with open(species_dat, "rb") as fh:
            data = _rubymarshal_load(fh)
    except Exception as exc:
        log.warning("Failed to parse %s: %s", species_dat, exc)
        return entries

    for key, obj in data.items():
        # species.dat is keyed by both integer and Symbol; skip duplicates
        if isinstance(key, int):
            continue
        if not isinstance(obj, RubyObject):
            continue

        attrs = obj.attributes
        form = attrs.get("@form", 0)
        if form != 0:
            continue  # skip alternate forms

        species_id = attrs.get("@id")
        if species_id is None:
            continue
        species_name = _ruby_symbol_str(species_id)

        # "real_" prefix is Pokémon Essentials' convention for translatable
        # text fields (the non-translated source string).
        raw_entry = attrs.get("@real_pokedex_entry", "")
        entry_text = _clean_entry_text(_ruby_bytes_str(raw_entry))
        if entry_text:
            entries[species_name] = entry_text

    log.info("Parsed %d Pokédex entries from %s", len(entries), species_dat.name)
    return entries


def build_species_id_map(species_dat: Path) -> dict:
    """
    Parse ``Data/species.dat`` and return a ``{dex_number: SPECIES_NAME}``
    mapping.  Used to resolve numeric IDs in KIF's JSON Pokédex files.
    """
    id_map: dict = {}

    if not HAS_RUBYMARSHAL or not species_dat.is_file():
        return id_map

    try:
        with open(species_dat, "rb") as fh:
            data = _rubymarshal_load(fh)
    except Exception:
        return id_map

    for key, obj in data.items():
        if not isinstance(key, int):
            continue
        if not isinstance(obj, RubyObject):
            continue
        attrs = obj.attributes
        if attrs.get("@form", 0) != 0:
            continue
        species_id = attrs.get("@id")
        if species_id is None:
            continue
        id_map[key] = _ruby_symbol_str(species_id)

    return id_map


def parse_kif_fusion_json(game_dir: Path, id_map: dict) -> tuple[dict, dict]:
    """
    Parse KIF's ``Data/pokedex/dex.json`` and return two dicts:

    1. ``{(SPECIES1, SPECIES2): entry_text}`` — primary (first) entry per pair
    2. ``{(SPECIES1, SPECIES2): [entry_text, ...]}`` — variant entries (2nd, 3rd, …)

    *id_map* must be a ``{dex_number: SPECIES_NAME}`` mapping (from
    :func:`build_species_id_map`).
    """
    primary_entries: dict = {}
    variant_entries: dict = {}
    all_per_pair: dict = {}  # accumulates all entries per pair

    dex_json = game_dir / "Data" / "pokedex" / "dex.json"

    if not dex_json.is_file():
        return primary_entries, variant_entries

    try:
        content = dex_json.read_text(encoding="utf-8", errors="replace")
        records = json.loads(content)
    except (OSError, json.JSONDecodeError) as exc:
        log.warning("Cannot read %s: %s", dex_json, exc)
        return primary_entries, variant_entries

    for rec in records:
        sprite = rec.get("sprite", "")
        entry_text = _clean_entry_text(rec.get("entry", ""))
        if not entry_text or not sprite:
            continue

        # Sprite format: "head.body.png" or "head.body_variant.png"
        base = sprite.rsplit(".png", 1)[0] if sprite.endswith(".png") else sprite
        parts = base.split(".", 1)
        if len(parts) != 2:
            continue

        try:
            head_id = int(parts[0])
            # Body may contain variant suffix like "4a"; strip non-digits
            body_num = re.match(r"(\d+)", parts[1])
            if not body_num:
                continue
            body_id = int(body_num.group(1))
        except ValueError:
            continue

        head_name = id_map.get(head_id)
        body_name = id_map.get(body_id)
        if not head_name or not body_name:
            continue

        pair = (head_name, body_name)
        # Collect all unique entries per pair
        if pair not in all_per_pair:
            all_per_pair[pair] = []
        if entry_text not in all_per_pair[pair]:
            all_per_pair[pair].append(entry_text)

    # Split into primary (first entry) and variants (subsequent entries)
    for pair, texts in all_per_pair.items():
        primary_entries[pair] = texts[0]
        if len(texts) > 1:
            variant_entries[pair] = texts[1:]

    if primary_entries:
        log.info("Parsed %d fusion entries from %s", len(primary_entries), dex_json.name)
    if variant_entries:
        variant_count = sum(len(v) for v in variant_entries.values())
        log.info(
            "Found %d additional variant entries across %d fusion pairs",
            variant_count, len(variant_entries),
        )
    return primary_entries, variant_entries


# ---------------------------------------------------------------------------
# Registration.rb parsing (Data/Scripts/990_NPT/001_Registration.rb etc.)
# ---------------------------------------------------------------------------

# Regex to find each GameData::Species.register({...}) block.  The outer
# braces may contain nested hash literals (e.g. base_stats: { ... }), so we
# cannot just match the first '}' — instead we count brace depth.
_REGISTER_START_RE = re.compile(
    r"GameData::Species\.register\(\{", re.MULTILINE
)

# Field extractors applied to the text inside a single register block.
_REG_ID_RE = re.compile(r"(?:^|\s)id:\s+:(\w+)", re.MULTILINE)
_REG_ID_NUMBER_RE = re.compile(r"(?:^|\s)id_number:\s+(\d+)", re.MULTILINE)
_REG_DEX_ENTRY_RE = re.compile(
    r'pokedex_entry:\s*"((?:[^"\\]|\\.)*)"', re.DOTALL
)


def _extract_register_blocks(content: str) -> list[str]:
    """Return the text of each ``GameData::Species.register({...})`` block.

    Handles nested braces (e.g. ``base_stats: { ... }``) by tracking brace
    depth rather than relying on a single closing ``}``.
    """
    blocks: list[str] = []
    for m in _REGISTER_START_RE.finditer(content):
        # Start just after the opening '{'
        start = m.end()
        depth = 1
        i = start
        while i < len(content) and depth > 0:
            ch = content[i]
            if ch == "{":
                depth += 1
            elif ch == "}":
                depth -= 1
            elif ch == '"':
                # Skip over string literals so braces inside strings are
                # not counted.
                i += 1
                while i < len(content) and content[i] != '"':
                    if content[i] == "\\":
                        i += 1  # skip escaped character
                    i += 1
            elif ch == "#":
                # Skip single-line comments
                while i < len(content) and content[i] != "\n":
                    i += 1
            i += 1
        # depth == 0 → we found the matching '})'; extract the inner text
        if depth == 0:
            blocks.append(content[start : i - 1])
    return blocks


def parse_registration_rb(rb_file: Path) -> tuple[dict, dict]:
    """
    Parse a KIF Ruby registration script and return two dicts:

    1. ``{SPECIES_NAME: entry_text}``  — Pokédex descriptions
    2. ``{id_number: SPECIES_NAME}``   — numeric-ID-to-name mapping (for
       fusion resolution via :func:`parse_kif_fusion_json`)

    The expected format is ``GameData::Species.register({...})`` blocks
    containing at minimum ``id:``, ``id_number:``, and ``pokedex_entry:``
    fields (KIF's ``Data/Scripts/990_NPT/001_Registration.rb``).
    """
    entries: dict = {}
    id_map: dict = {}

    if not rb_file.is_file():
        log.debug("Registration script not found: %s", rb_file)
        return entries, id_map

    try:
        content = rb_file.read_text(encoding="utf-8", errors="replace")
    except OSError as exc:
        log.warning("Cannot read %s: %s", rb_file, exc)
        return entries, id_map

    blocks = _extract_register_blocks(content)

    for block in blocks:
        id_match = _REG_ID_RE.search(block)
        if not id_match:
            continue
        species_name = id_match.group(1).upper()

        # id_number (optional — only needed for fusion ID mapping)
        num_match = _REG_ID_NUMBER_RE.search(block)
        if num_match:
            try:
                id_number = int(num_match.group(1))
                id_map[id_number] = species_name
            except ValueError:
                pass

        # pokedex_entry
        entry_match = _REG_DEX_ENTRY_RE.search(block)
        if not entry_match:
            continue
        raw_text = entry_match.group(1)
        entry_text = _clean_entry_text(raw_text)
        if entry_text:
            entries[species_name] = entry_text

    if entries:
        log.info(
            "Parsed %d Pokédex entries (%d with id_number) from %s",
            len(entries),
            len(id_map),
            rb_file.name,
        )
    return entries, id_map


def find_registration_scripts(game_dir: Path) -> list[Path]:
    """Discover Registration.rb files under ``Data/Scripts/``.

    Returns a list of paths, checking:
    - ``Data/Scripts/990_NPT/001_Registration.rb`` (primary known location)
    - Any ``*.rb`` files under ``Data/Scripts/990_NPT/``
    - Any file matching ``**/001_Registration.rb`` elsewhere in ``Data/Scripts/``
    """
    scripts_dir = game_dir / "Data" / "Scripts"
    found: list[Path] = []
    seen: set[Path] = set()

    # Primary known location
    primary = scripts_dir / "990_NPT" / "001_Registration.rb"
    if primary.is_file():
        found.append(primary)
        seen.add(primary.resolve())

    # Any other .rb files in the 990_NPT directory
    npt_dir = scripts_dir / "990_NPT"
    if npt_dir.is_dir():
        for rb in sorted(npt_dir.glob("*.rb")):
            if rb.resolve() not in seen:
                found.append(rb)
                seen.add(rb.resolve())

    # Glob for Registration.rb elsewhere in Data/Scripts/
    if scripts_dir.is_dir():
        for rb in sorted(scripts_dir.glob("**/001_Registration.rb")):
            if rb.resolve() not in seen:
                found.append(rb)
                seen.add(rb.resolve())

    return found


# ---------------------------------------------------------------------------
# TTS generation
# ---------------------------------------------------------------------------

def _generate_pyttsx3(text: str, out_wav: Path, speech_rate: int = 130,
                      voice_index: int = 0) -> None:
    """Synthesise *text* with pyttsx3 and save as WAV to *out_wav*.

    *speech_rate* is the words-per-minute speaking speed passed to SAPI.
    130 wpm is slightly slower than natural speech, which gives the measured,
    deliberate cadence associated with the classic Pokédex narrator.
    """
    engine = pyttsx3.init()
    voices = engine.getProperty("voices")
    if voices and voice_index < len(voices):
        engine.setProperty("voice", voices[voice_index].id)
    engine.setProperty("rate", speech_rate)
    engine.setProperty("volume", 1.0)
    engine.save_to_file(text, str(out_wav))
    engine.runAndWait()
    engine.stop()


def _generate_gtts(text: str, out_mp3: Path) -> None:
    """Synthesise *text* with gTTS and save as MP3 to *out_mp3*."""
    tts = gTTS(text=text, lang="en", slow=False)
    tts.save(str(out_mp3))


# ---------------------------------------------------------------------------
# FakeYou TTS  (uses the real "Pokedex (Pokemon, 4Kids)" AI voice model)
# ---------------------------------------------------------------------------
# Same approach as github.com/adriantwarog/Pokedex-RL — calls the FakeYou
# REST API with the community-trained Pokédex Dexter voice model.

_FAKEYOU_MODEL_TOKEN = "weight_dh8zry5bgkfm0z6nv3anqa9y5"
_FAKEYOU_LOGIN_URL = "https://api.fakeyou.com/v1/login"
_FAKEYOU_INFERENCE_URL = "https://api.fakeyou.com/tts/inference"
_FAKEYOU_JOB_URL = "https://api.fakeyou.com/tts/job/{}"
_FAKEYOU_AUDIO_BASE = "https://cdn-2.fakeyou.com"
# Fallback for environments where the primary CDN is not yet propagated
_FAKEYOU_AUDIO_BASE_FALLBACK = "https://storage.googleapis.com/vocodes-public"

# Polling settings for waiting on FakeYou job completion
_FAKEYOU_POLL_INTERVAL = 5      # seconds between status checks
_FAKEYOU_MAX_WAIT = 300         # give up after this many seconds (anonymous queue can be slow)
_FAKEYOU_RATE_LIMIT_WAIT = 15   # pause when rate-limited
_FAKEYOU_DOWNLOAD_RETRIES = 3   # number of download attempts before giving up
_FAKEYOU_DOWNLOAD_BACKOFF = 5   # seconds to wait between download retries


def _sanitize_fakeyou_cookie(raw: str) -> str:
    """Extract the session token value from various cookie formats.

    Users may pass the cookie in different ways:
      - Plain token value:       ``abc123``
      - With session= prefix:    ``session=abc123``
      - Full cookie header:      ``session=abc123; _ga=GA...``
      - With Cookie: prefix:     ``Cookie: session=abc123``

    This helper normalises all of these to the bare token value.
    """
    raw = raw.strip()
    if not raw:
        return ""

    # Strip optional "Cookie:" prefix (case-insensitive)
    if raw.lower().startswith("cookie:"):
        raw = raw[len("cookie:"):].strip()

    # If the string contains "session=", extract that cookie's value
    match = re.search(r"(?:^|;\s*)session=([^;]+)", raw)
    if match:
        return match.group(1).strip()

    # Otherwise treat the whole thing as a bare token value
    return raw


def _fakeyou_login(username: str, password: str) -> str:
    """Log in to FakeYou and return the session cookie token.

    Calls the ``/v1/login`` endpoint with the given credentials and
    extracts the ``session`` cookie from the response.

    Raises
    ------
    RuntimeError
        If login fails or no session cookie is returned.
    """
    resp = _requests.post(
        _FAKEYOU_LOGIN_URL,
        json={"username_or_email": username, "password": password},
        headers={"Content-Type": "application/json", "Accept": "application/json"},
        timeout=30,
    )

    if resp.status_code == 401:
        raise RuntimeError(
            "FakeYou login failed: invalid username/email or password."
        )
    resp.raise_for_status()

    result = resp.json()
    if not result.get("success"):
        raise RuntimeError(
            f"FakeYou login failed: "
            f"{result.get('error_reason', 'unknown error')}"
        )

    # Extract session cookie from the response Set-Cookie header.
    # resp.cookies is preferred; the raw header fallback is defensive
    # in case the requests library's cookie jar misses it.
    session_cookie = resp.cookies.get("session", "")
    if not session_cookie:
        # Try parsing from raw Set-Cookie header as fallback
        set_cookie = resp.headers.get("set-cookie", "")
        match = re.search(r"session=([^;]+)", set_cookie)
        if match:
            session_cookie = match.group(1)

    if not session_cookie:
        raise RuntimeError(
            "FakeYou login succeeded but no session cookie was returned."
        )

    log.info("FakeYou: logged in successfully as '%s'", username)
    return session_cookie


def _generate_fakeyou(text: str, out_wav: Path, cookie: str = "") -> None:
    """Synthesise *text* with the FakeYou Pokédex voice model.

    Submits a TTS inference job, polls until complete, and downloads
    the resulting WAV file to *out_wav*.

    Parameters
    ----------
    text : str
        The Pokédex entry text to speak.
    out_wav : Path
        Destination file path (WAV format).
    cookie : str
        Optional FakeYou session cookie for priority queue access.
        Without it, jobs go into the anonymous (slower) queue.
    """
    headers = {"Content-Type": "application/json", "Accept": "application/json"}
    if cookie:
        headers["Cookie"] = f"session={cookie}"

    # 1. Submit TTS inference job
    payload = {
        "tts_model_token": _FAKEYOU_MODEL_TOKEN,
        "uuid_idempotency_token": str(uuid.uuid4()),
        "inference_text": text,
    }
    resp = _requests.post(
        _FAKEYOU_INFERENCE_URL,
        headers=headers,
        json=payload,
        timeout=30,
    )
    resp.raise_for_status()
    result = resp.json()

    if not result.get("success"):
        raise RuntimeError(
            f"FakeYou inference request failed: "
            f"{result.get('error_reason', 'unknown error')}"
        )

    job_token = result.get("inference_job_token")
    if not job_token:
        raise RuntimeError("FakeYou returned no inference_job_token")

    log.debug("FakeYou job submitted: %s", job_token)

    # 2. Poll until the job finishes
    elapsed = 0
    status = "unknown"
    while elapsed < _FAKEYOU_MAX_WAIT:
        time.sleep(_FAKEYOU_POLL_INTERVAL)
        elapsed += _FAKEYOU_POLL_INTERVAL

        try:
            poll_resp = _requests.get(
                _FAKEYOU_JOB_URL.format(job_token),
                headers=headers,
                timeout=30,
            )
        except _requests.RequestException as exc:
            log.debug("FakeYou poll request failed: %s", exc)
            continue
        if poll_resp.status_code == 429:
            log.debug("FakeYou rate-limited, waiting %ds…", _FAKEYOU_RATE_LIMIT_WAIT)
            time.sleep(_FAKEYOU_RATE_LIMIT_WAIT)
            elapsed += _FAKEYOU_RATE_LIMIT_WAIT
            continue
        poll_resp.raise_for_status()
        state = poll_resp.json().get("state", {})
        status = state.get("status", "unknown")

        log.debug("  Job %s status: %s (%.0fs)", job_token, status, elapsed)

        if status == "complete_success":
            # Build candidate download URLs.
            # Prefer a full result URL returned by the API (future-proof);
            # fall back to constructing the URL from the audio path and
            # the known CDN base(s).
            audio_urls: list[str] = []

            full_url = state.get("maybe_result_url") or state.get("result_url")
            if full_url:
                audio_urls.append(full_url)

            wav_path = state.get("maybe_public_bucket_wav_audio_path")
            if wav_path:
                audio_urls.append(f"{_FAKEYOU_AUDIO_BASE}{wav_path}")
                audio_urls.append(f"{_FAKEYOU_AUDIO_BASE_FALLBACK}{wav_path}")

            if not audio_urls:
                raise RuntimeError("FakeYou job succeeded but returned no audio path")

            # Use plain headers for CDN download (no JSON content-type).
            # Include the session cookie when downloading from FakeYou's
            # own CDN, but omit it for third-party hosts.
            dl_headers: dict[str, str] = {}
            if cookie:
                dl_headers["Cookie"] = f"session={cookie}"

            # 3. Download the WAV file — try each candidate URL in order
            last_exc: Exception | None = None
            for audio_url in audio_urls:
                # Only send the session cookie to FakeYou's own domains;
                # skip it for third-party CDNs (e.g. googleapis.com).
                parsed_host = urllib.parse.urlparse(audio_url).hostname or ""
                is_fakeyou = (
                    parsed_host == "fakeyou.com"
                    or parsed_host.endswith(".fakeyou.com")
                )
                use_headers = dl_headers if is_fakeyou else {}
                for attempt in range(1, _FAKEYOU_DOWNLOAD_RETRIES + 1):
                    try:
                        audio_resp = _requests.get(
                            audio_url, headers=use_headers, timeout=60,
                        )
                        audio_resp.raise_for_status()
                        out_wav.write_bytes(audio_resp.content)
                        log.debug("Downloaded FakeYou audio: %s", out_wav)
                        return
                    except _requests.RequestException as exc:
                        last_exc = exc
                        if attempt < _FAKEYOU_DOWNLOAD_RETRIES:
                            log.debug(
                                "FakeYou download attempt %d/%d failed (%s), "
                                "retrying in %ds…",
                                attempt, _FAKEYOU_DOWNLOAD_RETRIES, exc,
                                _FAKEYOU_DOWNLOAD_BACKOFF,
                            )
                            time.sleep(_FAKEYOU_DOWNLOAD_BACKOFF)
                log.warning(
                    "All %d download retries exhausted for URL: %s",
                    _FAKEYOU_DOWNLOAD_RETRIES, audio_url,
                )

            raise RuntimeError(
                f"Failed to download FakeYou audio from "
                f"{audio_urls}: {last_exc}"
            ) from last_exc

        if status in ("dead", "attempt_failed", "complete_failure"):
            raise RuntimeError(f"FakeYou job failed with status: {status}")

        # "pending", "started", "attempt_pending" → keep polling

    raise RuntimeError(
        f"FakeYou job timed out after {_FAKEYOU_MAX_WAIT}s (last status: {status})"
    )


def _apply_dexter_effect(audio: "AudioSegment") -> "AudioSegment":
    """
    Apply post-processing to make the voice sound like Dexter from the
    classic Pokémon anime:

    1. High-pass filter  — removes bass, gives a thin, broadcast-radio quality
    2. Low-pass filter   — softens harsh high frequencies
    3. Echo overlay      — adds the characteristic resonant 'robot' quality
    4. Normalise         — ensures consistent loudness
    """
    # Band-pass simulation: cut below 350 Hz and above 4 000 Hz
    audio = audio.high_pass_filter(350)
    audio = audio.low_pass_filter(4000)

    # Subtle echo: quieter copy delayed by ~35 ms gives robotic resonance
    echo = audio - 13          # 13 dB quieter
    audio = audio.overlay(echo, position=35)

    audio = normalize(audio)
    return audio


def generate_voice_file(text: str, dest_ogg: Path, backend: str = "auto",
                        voice_index: int = 0,
                        fakeyou_cookie: str = "") -> tuple[bool, str]:
    """
    Generate a single voiced OGG file at *dest_ogg*.

    Returns (True, "") on success, (False, reason) on failure.
    """
    dest_ogg = Path(dest_ogg)
    dest_ogg.parent.mkdir(parents=True, exist_ok=True)

    with tempfile.TemporaryDirectory() as tmp_dir:
        tmp = Path(tmp_dir)

        # ---- step 1: raw TTS -----------------------------------------------
        raw_path: Path | None = None
        used_fakeyou = False
        failure_reason = ""

        if backend == "fakeyou" and HAS_REQUESTS:
            raw_path = tmp / "raw.wav"
            try:
                _generate_fakeyou(text, raw_path, cookie=fakeyou_cookie)
                used_fakeyou = True
            except Exception as exc:
                log.error("FakeYou failed: %s", exc)
                failure_reason = str(exc)
                raw_path = None

        if raw_path is None and backend in ("pyttsx3", "auto") and HAS_PYTTSX3:
            raw_path = tmp / "raw.wav"
            try:
                _generate_pyttsx3(text, raw_path, voice_index=voice_index)
                failure_reason = ""
            except Exception as exc:
                log.debug("pyttsx3 failed: %s", exc)
                if not failure_reason:
                    failure_reason = str(exc)
                raw_path = None

        if raw_path is None and backend in ("gtts", "auto") and HAS_GTTS:
            raw_path = tmp / "raw.mp3"
            try:
                _generate_gtts(text, raw_path)
                failure_reason = ""
            except Exception as exc:
                log.debug("gTTS failed: %s", exc)
                if not failure_reason:
                    failure_reason = str(exc)
                raw_path = None

        if raw_path is None or not raw_path.exists():
            reason = failure_reason or "No TTS backend produced output"
            log.error(
                "No TTS backend produced output.  "
                "Install pyttsx3 (offline) or gTTS (online), "
                "or use --backend fakeyou (requires internet)."
            )
            return False, reason

        # ---- step 2: audio effects + export --------------------------------
        # FakeYou already uses the real Pokédex AI voice model so the Dexter
        # post-processing effects are unnecessary and would degrade quality.
        if HAS_PYDUB and HAS_FFMPEG:
            try:
                audio = AudioSegment.from_file(str(raw_path))
                if not used_fakeyou:
                    audio = _apply_dexter_effect(audio)
                audio.export(
                    str(dest_ogg),
                    format="ogg",
                    parameters=["-q:a", "5"],
                )
            except Exception as exc:
                log.error("pydub processing failed: %s", exc)
                # Fall back to raw copy
                shutil.copy(str(raw_path), str(dest_ogg.with_suffix(raw_path.suffix)))
                return True, ""
        else:
            # No pydub or no ffmpeg — save the raw audio without Dexter effects.
            # The user has already been warned at startup; no per-file message needed.
            fallback = dest_ogg.with_suffix(raw_path.suffix)
            shutil.copy(str(raw_path), str(fallback))

    return True, ""


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def list_voices() -> int:
    if not HAS_PYTTSX3:
        print("pyttsx3 is not installed.  Run:  pip install pyttsx3")
        return 1
    engine = pyttsx3.init()
    voices = engine.getProperty("voices")
    if not voices:
        print("No voices found.")
        engine.stop()
        return 0
    print("Available pyttsx3 voices:")
    for i, v in enumerate(voices):
        print(f"  [{i}]  {v.name}")
        print(f"        id: {v.id}")
    engine.stop()
    return 0


def build_arg_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        description="Generate Pokédex voice-over audio files for the KIF mod.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    p.add_argument(
        "--game-dir",
        metavar="PATH",
        help="Path to your KIF game root directory (contains Data/ and/or PBS/, Mods/, etc.).",
    )
    p.add_argument(
        "--pbs-file",
        metavar="PATH",
        help=(
            "Explicit path to a PBS pokemon.txt file.  "
            "Use this if your game stores PBS data in a non-standard location."
        ),
    )
    p.add_argument(
        "--registration-file",
        metavar="PATH",
        action="append",
        default=None,
        help=(
            "Explicit path to a KIF Registration.rb script that contains "
            "GameData::Species.register({...}) blocks.  May be specified "
            "multiple times.  If omitted, the script auto-discovers "
            "Registration.rb files under Data/Scripts/."
        ),
    )
    p.add_argument(
        "--species",
        metavar="NAME",
        help="Generate a file for one species only (e.g. BULBASAUR).",
    )
    fusions_group = p.add_mutually_exclusive_group()
    fusions_group.add_argument(
        "--fusions",
        action="store_true",
        default=True,
        help="Generate voice files for fusion Pokédex entries (default: on).",
    )
    fusions_group.add_argument(
        "--no-fusions",
        dest="fusions",
        action="store_false",
        help="Skip fusion Pokédex entries — generate only regular Pokémon.",
    )
    p.add_argument(
        "--retry-failed",
        action="store_true",
        help=(
            "Re-attempt only the entries that failed in a previous run.  "
            "Reads failed_entries.json from the output directory and retries "
            "only those entries.  Successful retries are removed from the log; "
            "entries that fail again remain in it."
        ),
    )
    p.add_argument(
        "--overwrite",
        action="store_true",
        help="Overwrite existing audio files (default: skip).",
    )
    p.add_argument(
        "--backend",
        choices=["auto", "pyttsx3", "gtts", "fakeyou"],
        default="auto",
        help=(
            "TTS backend.  'fakeyou' (RECOMMENDED) uses the FakeYou AI voice "
            "model trained on the real anime Pokédex voice.  'auto' tries "
            "pyttsx3 then gTTS as offline/generic fallbacks (default: auto)."
        ),
    )
    p.add_argument(
        "--fakeyou-cookie",
        metavar="COOKIE",
        help=(
            "FakeYou session cookie for authenticated (priority-queue) access.  "
            "May also be set via the FAKEYOU_COOKIE environment variable.  "
            "Without this, jobs use the anonymous queue which is slower."
        ),
    )
    p.add_argument(
        "--fakeyou-username",
        metavar="USER",
        help=(
            "FakeYou account username or email.  Used with --fakeyou-password "
            "to log in automatically and obtain a session cookie."
        ),
    )
    p.add_argument(
        "--fakeyou-password",
        metavar="PASS",
        help=(
            "FakeYou account password.  Used with --fakeyou-username "
            "to log in automatically.  May also be set via the "
            "FAKEYOU_PASSWORD environment variable."
        ),
    )
    p.add_argument(
        "--voice",
        type=int,
        default=0,
        metavar="INDEX",
        help="pyttsx3 voice index (see --list-voices).  Default: 0.",
    )
    p.add_argument(
        "--list-voices",
        action="store_true",
        help="Print available pyttsx3 voices and exit.",
    )
    p.add_argument(
        "--verbose", "-v",
        action="store_true",
        help="Show debug output.",
    )
    return p


def main(argv=None) -> int:
    parser = build_arg_parser()
    args = parser.parse_args(argv)

    if args.verbose:
        log.setLevel(logging.DEBUG)
        logging.getLogger().setLevel(logging.DEBUG)

    # ---- list-voices shortcut -----------------------------------------------
    if args.list_voices:
        return list_voices()

    # ---- validate required args ---------------------------------------------
    if not args.game_dir:
        parser.error("--game-dir is required (unless using --list-voices).")

    game_dir = Path(args.game_dir)
    if not game_dir.is_dir():
        log.error("Game directory not found: %s", game_dir)
        return 1

    # ---- check at least one TTS backend is available ------------------------
    fakeyou_cookie = args.fakeyou_cookie or os.environ.get("FAKEYOU_COOKIE", "")
    fakeyou_cookie = _sanitize_fakeyou_cookie(fakeyou_cookie)

    # FakeYou login: obtain a fresh session cookie from username/password
    fakeyou_user = args.fakeyou_username or os.environ.get("FAKEYOU_USERNAME", "")
    fakeyou_pass = args.fakeyou_password or os.environ.get("FAKEYOU_PASSWORD", "")
    if fakeyou_user and fakeyou_pass and not fakeyou_cookie:
        if not HAS_REQUESTS:
            log.error(
                "FakeYou login requires the 'requests' package.\n"
                "Run:  pip install requests"
            )
            return 1
        try:
            fakeyou_cookie = _fakeyou_login(fakeyou_user, fakeyou_pass)
        except RuntimeError as exc:
            log.error("FakeYou login failed: %s", exc)
            return 1

    if args.backend == "fakeyou":
        if not HAS_REQUESTS:
            log.error(
                "FakeYou backend requires the 'requests' package.\n"
                "Run:  pip install requests"
            )
            return 1
        if fakeyou_cookie:
            log.info("FakeYou: using authenticated session (cookie provided)")
        else:
            log.info(
                "FakeYou: no cookie provided — using anonymous queue (slower).\n"
                "  Set FAKEYOU_COOKIE env var or use --fakeyou-cookie for "
                "priority access."
            )
    elif not HAS_PYTTSX3 and not HAS_GTTS:
        log.error(
            "No TTS backend found.  "
            "Run:  pip install pyttsx3       (offline, generic voice)\n"
            "  or: pip install gTTS          (online, generic voice)\n"
            "  or: pip install requests      (for --backend fakeyou — "
            "RECOMMENDED, real anime voice)"
        )
        return 1

    if not HAS_PYDUB:
        log.warning(
            "pydub is not installed — Dexter audio effects will be skipped.\n"
            "Run:  pip install -r tools/requirements.txt\n"
            "Also ensure ffmpeg is installed and on your PATH."
        )
    elif not HAS_FFMPEG:
        log.warning(
            "ffmpeg not found on PATH — Dexter audio effects will be skipped.\n"
            "Install ffmpeg and add it to your PATH:\n"
            "  Windows: https://ffmpeg.org/download.html  (add the bin/ folder to PATH)\n"
            "           or:  winget install ffmpeg  /  choco install ffmpeg\n"
            "  macOS:   brew install ffmpeg\n"
            "  Linux:   sudo apt install ffmpeg\n"
            "After installing, open a new terminal so the updated PATH takes effect."
        )

    # ---- resolve output directory -------------------------------------------
    output_dir = game_dir / "Audio" / "SE" / "Pokedex"
    output_dir.mkdir(parents=True, exist_ok=True)
    log.info("Output directory: %s", output_dir)

    # ---- parse Pokédex data -------------------------------------------------
    # Strategy: try Data/species.dat (KIF) first, then PBS/pokemon.txt (PIF),
    # then an explicit --pbs-file if given.
    all_entries: dict = {}
    species_id_map: dict = {}
    species_dat = game_dir / "Data" / "species.dat"

    # 1. KIF Data/species.dat (requires rubymarshal)
    if species_dat.is_file():
        if HAS_RUBYMARSHAL:
            all_entries = parse_species_dat(species_dat)
            species_id_map = build_species_id_map(species_dat)
        else:
            log.info(
                "Found %s but rubymarshal is not installed.\n"
                "  Run:  pip install rubymarshal\n"
                "  to enable reading Pokédex data directly from the KIF game data.",
                species_dat,
            )

    # 2. PBS/pokemon.txt (vanilla PIF or manually extracted)
    if not all_entries:
        pbs_file = Path(args.pbs_file) if args.pbs_file else game_dir / "PBS" / "pokemon.txt"
        if pbs_file.is_file():
            all_entries = parse_pbs_pokemon(pbs_file)

    # 3. Registration.rb scripts (Data/Scripts/990_NPT/001_Registration.rb
    #    and similar) — supplementary source that adds species which may not
    #    be present in species.dat or PBS.
    reg_files: list[Path] = []
    if args.registration_file:
        reg_files = [Path(p) for p in args.registration_file]
    else:
        reg_files = find_registration_scripts(game_dir)

    reg_total_entries = 0
    for rf in reg_files:
        rb_entries, rb_id_map = parse_registration_rb(rf)
        # Merge without overwriting — species.dat / PBS entries take priority
        for name, text in rb_entries.items():
            if name not in all_entries:
                all_entries[name] = text
                reg_total_entries += 1
        for num, name in rb_id_map.items():
            if num not in species_id_map:
                species_id_map[num] = name
    if reg_total_entries:
        log.info(
            "Registration scripts added %d new Pokédex entries (total now %d)",
            reg_total_entries,
            len(all_entries),
        )

    # 4. Give up with a helpful error
    if not all_entries:
        has_species_dat = species_dat.is_file()
        if has_species_dat and not HAS_RUBYMARSHAL:
            log.error(
                "No Pokédex entries found.\n"
                "  Your game has Data/species.dat but rubymarshal is not installed.\n"
                "  Fix:  pip install rubymarshal"
            )
        else:
            log.error(
                "No Pokédex entries found.\n"
                "  Make sure --game-dir points to the KIF game root directory\n"
                "  (the folder that contains Game.exe and the Data/ directory).\n"
                "  Checked:\n"
                "    - %s  (not found)\n"
                "    - %s  (not found)\n"
                "    - Data/Scripts/**/001_Registration.rb  (not found)\n"
                "  If your PBS file is elsewhere, use --pbs-file to specify its path.\n"
                "  If you have a Registration.rb file, use --registration-file.",
                species_dat,
                game_dir / "PBS" / "pokemon.txt",
            )
        return 1

    # ---- filter to single species if requested ------------------------------
    if args.species:
        key = args.species.strip().upper()
        if key not in all_entries:
            log.error("Species '%s' not found in Pokédex data.", key)
            return 1
        all_entries = {key: all_entries[key]}

    # ---- load existing failure log ------------------------------------------
    failure_log_path = output_dir / "failed_entries.json"
    failure_log: dict = {}
    if failure_log_path.exists():
        try:
            with open(failure_log_path, encoding="utf-8") as fh:
                failure_log = json.load(fh)
        except Exception as exc:
            log.warning("Could not read failure log %s: %s", failure_log_path, exc)
            failure_log = {}

    # ---- build fusion entry map (needed even for --retry-failed) ------------
    fusion_entries: dict = {}
    fusion_variant_entries: dict = {}  # {(SP1, SP2): [text2, text3, …]}
    if args.fusions:
        if species_id_map:
            fusion_entries, fusion_variant_entries = parse_kif_fusion_json(game_dir, species_id_map)
        if not fusion_entries:
            fusion_entries = parse_fusion_entries(game_dir)
        if not fusion_entries and not args.retry_failed:
            log.info(
                "No fusion Pokédex entries found.  "
                "KIF may use auto-generated fusion descriptions that are not "
                "stored in data files."
            )

    # ---- build a lookup: filename → (text, dest) for retry mode ------------
    def _all_pending_entries() -> list[tuple[str, str, Path]]:
        """Return list of (filename, text, dest) for all entries to process.

        Includes primary fusion entries and any variant entries (named with
        a ``_v2``, ``_v3``, … suffix).  Variant files are generated alongside
        primary files but never overwrite them.
        """
        items = []
        for species_name, entry_text in sorted(all_entries.items()):
            dest = output_dir / f"dex_{species_name}.ogg"
            items.append((dest.name, entry_text, dest))
        if args.fusions:
            for (sp1, sp2), entry_text in sorted(fusion_entries.items()):
                dest = output_dir / f"dex_{sp1}_{sp2}.ogg"
                items.append((dest.name, entry_text, dest))
            # Variant entries for fusions with multiple dex descriptions
            for (sp1, sp2), variant_texts in sorted(fusion_variant_entries.items()):
                for idx, vtext in enumerate(variant_texts, start=2):
                    dest = output_dir / f"dex_{sp1}_{sp2}_v{idx}.ogg"
                    items.append((dest.name, vtext, dest))
        return items

    # ---- determine which entries to attempt ---------------------------------
    if args.retry_failed:
        if not failure_log:
            log.info("No failure log found at %s — nothing to retry.", failure_log_path)
            print("\nDone — generated: 0, skipped: 0, failed: 0")
            print(f"Audio files saved to: {output_dir}")
            return 0

        # Build lookup of all entries so we can find text for failed filenames
        all_pending = {fname: (text, dest) for fname, text, dest in _all_pending_entries()}
        retry_filenames = list(failure_log.keys())
        log.info(
            "Retry mode: attempting %d previously failed entries from %s",
            len(retry_filenames),
            failure_log_path,
        )
        pending: list[tuple[str, str, Path]] = []
        for fname in retry_filenames:
            if fname in all_pending:
                text, dest = all_pending[fname]
                pending.append((fname, text, dest))
            else:
                log.warning(
                    "Failed entry '%s' not found in current Pokédex data — skipping.",
                    fname,
                )
    else:
        pending = _all_pending_entries()

    # ---- load existing duration manifest (for merge on retry) ---------------
    durations_path = output_dir / "dex_durations.json"
    durations: dict = {}
    if durations_path.exists():
        try:
            with open(durations_path, encoding="utf-8") as fh:
                durations = json.load(fh)
        except Exception as exc:
            log.warning("Could not read duration manifest %s: %s", durations_path, exc)
            durations = {}

    # ---- process entries ----------------------------------------------------
    generated = skipped = failed = 0

    for filename, entry_text, dest in pending:
        # A fusion filename has two underscores: dex_SP1_SP2.ogg (count >= 2)
        # A regular filename has one:            dex_SPECIES.ogg  (count == 1)
        is_fusion = filename.count("_") >= 2

        if not args.overwrite and dest.exists() and not args.retry_failed:
            log.debug("Skipping %s (already exists)", filename)
            skipped += 1
            continue

        log.info("Generating%s: %s", " fusion" if is_fusion else "", filename)
        log.debug("  Text: %s", entry_text[:80])

        ok, reason = generate_voice_file(
            entry_text,
            dest,
            backend=args.backend,
            voice_index=args.voice,
            fakeyou_cookie=fakeyou_cookie,
        )
        if ok:
            generated += 1
            # Remove from failure log on success
            failure_log.pop(filename, None)
            # Record duration in manifest (requires pydub + ffmpeg)
            if HAS_PYDUB and HAS_FFMPEG and dest.exists():
                try:
                    audio = AudioSegment.from_file(str(dest))
                    durations[filename] = len(audio) / 1000.0
                except Exception as exc:
                    log.debug("Could not read duration for %s: %s", filename, exc)
        else:
            failed += 1
            failure_log[filename] = reason

    # ---- persist duration manifest ------------------------------------------
    if durations:
        try:
            with open(durations_path, "w", encoding="utf-8") as fh:
                json.dump(durations, fh, indent=2, sort_keys=True)
            log.info(
                "Duration manifest updated (%d entries): %s",
                len(durations),
                durations_path,
            )
        except Exception as exc:
            log.warning("Could not write duration manifest %s: %s", durations_path, exc)

    # ---- persist entry map (text → audio filename mapping) -----------------
    # Maps audio file stems (e.g. "dex_RATTATA_HOOTHOOT_v2") to the Pokédex
    # entry text that was used to generate the audio.  The mod uses this to
    # match the currently displayed entry text to the correct audio variant.
    entry_map: dict = {}
    for filename, entry_text, dest in _all_pending_entries():
        stem = dest.stem  # e.g. "dex_RATTATA_HOOTHOOT" or "dex_RATTATA_HOOTHOOT_v2"
        entry_map[stem] = entry_text

    if entry_map:
        entry_map_path = output_dir / "dex_entry_map.json"
        try:
            with open(entry_map_path, "w", encoding="utf-8") as fh:
                json.dump(entry_map, fh, indent=2, sort_keys=True)
            log.info(
                "Entry map written (%d entries): %s",
                len(entry_map),
                entry_map_path,
            )
        except Exception as exc:
            log.warning("Could not write entry map %s: %s", entry_map_path, exc)

    # ---- persist failure log ------------------------------------------------
    try:
        if failure_log:
            with open(failure_log_path, "w", encoding="utf-8") as fh:
                json.dump(failure_log, fh, indent=2)
            log.info(
                "Failure log updated (%d entries): %s",
                len(failure_log),
                failure_log_path,
            )
        elif failure_log_path.exists():
            # All entries succeeded — remove the now-empty log file
            failure_log_path.unlink()
    except Exception as exc:
        log.warning("Could not write failure log %s: %s", failure_log_path, exc)

    # ---- summary ------------------------------------------------------------
    print(
        f"\nDone — generated: {generated}, skipped: {skipped}, failed: {failed}"
    )
    print(f"Audio files saved to: {output_dir}")
    return 0 if failed == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
