#!/usr/bin/env python3
"""
Pokédex Voice-Over Generator for KIF (Kuray's Infinite Fusion)
==============================================================

Generates TTS audio files for every Pokédex entry in your KIF game,
voiced in the style of Dexter — the classic Pokémon anime Pokédex narrator.

The script reads Pokédex description text from the game's PBS data files,
synthesises speech, and exports OGG Vorbis audio files.

TTS backends
------------
  --backend fakeyou   (RECOMMENDED) Uses the FakeYou AI voice model
                      "Pokedex (Pokemon, 4Kids)" — a community-trained model
                      that replicates the real Dexter voice from the anime.
                      Same approach used by github.com/adriantwarog/Pokedex-RL.
                      Requires internet access.

  --backend pyttsx3   Offline fallback — uses OS built-in voices (SAPI on
                      Windows, NSSpeechSynthesizer on macOS, eSpeak on Linux)
                      with post-processing effects.

  --backend gtts      Online fallback — uses Google's Text-to-Speech API
                      with post-processing effects.

Output files are saved as OGG Vorbis to:
  <game-dir>/Mods/pokedex_voice_over/Audio/

Naming convention
-----------------
  dex_BULBASAUR.ogg               — regular Pokémon
  dex_BULBASAUR_CHARMANDER.ogg    — fused Pokémon (head_body)

Usage
-----
  # RECOMMENDED — Generate using the real anime Pokédex voice via FakeYou
  python generate_voices.py --game-dir /path/to/KIF --backend fakeyou

  # With FakeYou priority queue access (faster generation)
  python generate_voices.py --game-dir /path/to/KIF --backend fakeyou --fakeyou-cookie YOUR_COOKIE

  # Generate all regular Pokémon entries (creates files, skips existing ones)
  python generate_voices.py --game-dir /path/to/KIF

  # Overwrite any previously generated files
  python generate_voices.py --game-dir /path/to/KIF --overwrite

  # Generate for a single species only
  python generate_voices.py --game-dir /path/to/KIF --species BULBASAUR

  # Also generate fusion-specific entries (if your KIF build has them)
  # Fusions are now generated by default — use --no-fusions to skip
  python generate_voices.py --game-dir /path/to/KIF --no-fusions

  # With FakeYou login (auto-obtains session cookie)
  python generate_voices.py --game-dir /path/to/KIF --backend fakeyou --fakeyou-username YOU --fakeyou-password PASS

  # Use Google TTS instead of the default offline pyttsx3 backend
  python generate_voices.py --game-dir /path/to/KIF --backend gtts

  # Explicitly point to a PBS file (for non-standard installations)
  python generate_voices.py --game-dir /path/to/KIF --pbs-file /path/to/pokemon.txt

  # List available pyttsx3 voices and exit (useful for --voice selection)
  python generate_voices.py --list-voices

Requirements
------------
  pip install -r requirements.txt

  For --backend fakeyou:  requires the 'requests' package and internet access.

  For --backend pyttsx3:  On Windows, uses the built-in SAPI voices (e.g.
  "Microsoft David Desktop").  On macOS, it uses "Alex" or similar.  On
  Linux, it uses eSpeak.

  ffmpeg must be installed and on your PATH for pydub to export OGG files.
"""

import argparse
import json
import logging
import os
import re
import shutil
import sys
import tempfile
import time
import uuid
import warnings
from pathlib import Path

# ---------------------------------------------------------------------------
# Optional dependency detection
# ---------------------------------------------------------------------------

try:
    import pyttsx3
    HAS_PYTTSX3 = True
except ImportError:
    HAS_PYTTSX3 = False

try:
    from gtts import gTTS
    HAS_GTTS = True
except ImportError:
    HAS_GTTS = False

try:
    import requests as _requests
    HAS_REQUESTS = True
except ImportError:
    HAS_REQUESTS = False

try:
    # Suppress pydub's own RuntimeWarning about ffmpeg not being found at
    # import time — we perform our own explicit check below (HAS_FFMPEG).
    with warnings.catch_warnings():
        warnings.simplefilter("ignore", RuntimeWarning)
        from pydub import AudioSegment
        from pydub.effects import normalize
    HAS_PYDUB = True
except ImportError:
    HAS_PYDUB = False

# pydub requires ffmpeg (or avconv) to be on PATH for audio format conversion.
# Check once here so we can warn the user upfront instead of erroring per file.
HAS_FFMPEG = HAS_PYDUB and bool(shutil.which("ffmpeg") or shutil.which("avconv"))

try:
    from rubymarshal.reader import load as _rubymarshal_load
    from rubymarshal.classes import RubyObject as RubyObject
    HAS_RUBYMARSHAL = True
except ImportError:
    HAS_RUBYMARSHAL = False

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------

logging.basicConfig(
    level=logging.INFO,
    format="%(levelname)s: %(message)s",
)
log = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# PBS parsing
# ---------------------------------------------------------------------------

# Pokemon Essentials PBS pokemon.txt comes in two flavours:
#   Old (v18/v19 — used by vanilla PIF):  sections start with a numeric [001]
#   New (v20+):                            sections start with [INTERNAL_NAME]
# Both store the description in a  PokedexEntry=  key.

_PBS_SECTION_RE = re.compile(r"^\[(\w+)\]", re.MULTILINE)
_INTERNAL_NAME_RE = re.compile(r"^InternalName\s*=\s*(.+)$", re.MULTILINE)
_DEX_ENTRY_RE = re.compile(
    r"^PokedexEntry\s*=\s*(.+?)(?=\n\w|\Z)", re.MULTILINE | re.DOTALL
)


def _clean_entry_text(raw: str) -> str:
    """Normalise a raw Pokédex entry string for TTS consumption."""
    # Replace escaped newlines with a space
    text = raw.replace("\\n", " ")
    # Remove any remaining backslash escapes
    text = re.sub(r"\\.", " ", text)
    # Collapse whitespace
    text = re.sub(r"\s+", " ", text).strip()
    # Strip trailing punctuation inconsistencies
    if text and text[-1] not in ".!?":
        text += "."
    return text


def parse_pbs_pokemon(pbs_file: Path) -> dict:
    """
    Return a {SPECIES_NAME: entry_text} dict parsed from a PBS pokemon.txt.
    """
    entries: dict = {}

    if not pbs_file.is_file():
        log.warning("PBS file not found: %s", pbs_file)
        return entries

    try:
        content = pbs_file.read_text(encoding="utf-8", errors="replace")
    except OSError as exc:
        log.error("Cannot read %s: %s", pbs_file, exc)
        return entries

    # Split into per-Pokémon sections
    section_starts = [m.start() for m in _PBS_SECTION_RE.finditer(content)]
    for i, start in enumerate(section_starts):
        end = section_starts[i + 1] if i + 1 < len(section_starts) else len(content)
        section = content[start:end]

        # Determine the internal (species) name.
        # New-style PBS: the section header itself IS the internal name.
        header_match = _PBS_SECTION_RE.match(section)
        if not header_match:
            continue
        header_val = header_match.group(1)

        # Old-style PBS uses numeric section IDs, so we need InternalName=
        if header_val.isdigit():
            name_match = _INTERNAL_NAME_RE.search(section)
            if not name_match:
                continue
            species_name = name_match.group(1).strip().upper()
        else:
            species_name = header_val.upper()

        # Extract the Pokédex entry text
        entry_match = _DEX_ENTRY_RE.search(section)
        if not entry_match:
            continue

        raw_text = entry_match.group(1)
        entry_text = _clean_entry_text(raw_text)
        if entry_text:
            entries[species_name] = entry_text

    log.info("Parsed %d Pokédex entries from %s", len(entries), pbs_file.name)
    return entries


def parse_fusion_entries(game_dir: Path) -> dict:
    """
    Return a {(SPECIES1, SPECIES2): entry_text} dict from KIF fusion PBS data.

    KIF may store custom fusion Pokédex entries in various files; we attempt
    every known location.  Returns an empty dict if none are found.
    """
    fusion_entries: dict = {}

    candidate_files = [
        game_dir / "PBS" / "fusions.txt",
        game_dir / "PBS" / "fusion_dex.txt",
        game_dir / "PBS" / "fusionmon.txt",
    ]

    for path in candidate_files:
        if not path.is_file():
            continue
        log.info("Parsing fusion entries from %s", path)
        try:
            content = path.read_text(encoding="utf-8", errors="replace")
        except OSError as exc:
            log.warning("Cannot read %s: %s", path, exc)
            continue

        # Expected section format:
        #   [HEAD_BODY]
        #   PokedexEntry=...
        section_starts = [m.start() for m in _PBS_SECTION_RE.finditer(content)]
        for i, start in enumerate(section_starts):
            end = section_starts[i + 1] if i + 1 < len(section_starts) else len(content)
            section = content[start:end]

            header_match = _PBS_SECTION_RE.match(section)
            if not header_match:
                continue
            header_val = header_match.group(1).upper()

            # Expect a HEAD_BODY pair
            if "_" not in header_val:
                continue
            parts = header_val.split("_", 1)
            species1, species2 = parts[0], parts[1]

            entry_match = _DEX_ENTRY_RE.search(section)
            if not entry_match:
                continue
            raw_text = entry_match.group(1)
            entry_text = _clean_entry_text(raw_text)
            if entry_text:
                fusion_entries[(species1, species2)] = entry_text

    return fusion_entries


# ---------------------------------------------------------------------------
# KIF Data/ parsing (species.dat + JSON Pokédex files)
# ---------------------------------------------------------------------------

def _ruby_symbol_str(sym) -> str:
    """Convert a rubymarshal Symbol to a plain uppercase string."""
    if hasattr(sym, "name"):
        return sym.name.upper()
    return str(sym).lstrip(":").upper()


def _ruby_bytes_str(val) -> str:
    """Decode a rubymarshal bytes/string value to a Python str."""
    if isinstance(val, bytes):
        return val.decode("utf-8", errors="replace")
    return str(val) if val else ""


def parse_species_dat(species_dat: Path) -> dict:
    """
    Parse a KIF/Essentials ``Data/species.dat`` file and return a
    ``{SPECIES_NAME: entry_text}`` dict.

    Requires the ``rubymarshal`` package (``pip install rubymarshal``).
    Returns an empty dict if the file cannot be read or rubymarshal is not
    installed.
    """
    entries: dict = {}

    if not HAS_RUBYMARSHAL:
        log.debug("rubymarshal not installed — cannot parse species.dat")
        return entries

    if not species_dat.is_file():
        log.debug("species.dat not found: %s", species_dat)
        return entries

    try:
        with open(species_dat, "rb") as fh:
            data = _rubymarshal_load(fh)
    except Exception as exc:
        log.warning("Failed to parse %s: %s", species_dat, exc)
        return entries

    for key, obj in data.items():
        # species.dat is keyed by both integer and Symbol; skip duplicates
        if isinstance(key, int):
            continue
        if not isinstance(obj, RubyObject):
            continue

        attrs = obj.attributes
        form = attrs.get("@form", 0)
        if form != 0:
            continue  # skip alternate forms

        species_id = attrs.get("@id")
        if species_id is None:
            continue
        species_name = _ruby_symbol_str(species_id)

        # "real_" prefix is Pokémon Essentials' convention for translatable
        # text fields (the non-translated source string).
        raw_entry = attrs.get("@real_pokedex_entry", "")
        entry_text = _clean_entry_text(_ruby_bytes_str(raw_entry))
        if entry_text:
            entries[species_name] = entry_text

    log.info("Parsed %d Pokédex entries from %s", len(entries), species_dat.name)
    return entries


def build_species_id_map(species_dat: Path) -> dict:
    """
    Parse ``Data/species.dat`` and return a ``{dex_number: SPECIES_NAME}``
    mapping.  Used to resolve numeric IDs in KIF's JSON Pokédex files.
    """
    id_map: dict = {}

    if not HAS_RUBYMARSHAL or not species_dat.is_file():
        return id_map

    try:
        with open(species_dat, "rb") as fh:
            data = _rubymarshal_load(fh)
    except Exception:
        return id_map

    for key, obj in data.items():
        if not isinstance(key, int):
            continue
        if not isinstance(obj, RubyObject):
            continue
        attrs = obj.attributes
        if attrs.get("@form", 0) != 0:
            continue
        species_id = attrs.get("@id")
        if species_id is None:
            continue
        id_map[key] = _ruby_symbol_str(species_id)

    return id_map


def parse_kif_fusion_json(game_dir: Path, id_map: dict) -> dict:
    """
    Parse KIF's ``Data/pokedex/dex.json`` and return a
    ``{(SPECIES1, SPECIES2): entry_text}`` dict for fusion Pokémon.

    *id_map* must be a ``{dex_number: SPECIES_NAME}`` mapping (from
    :func:`build_species_id_map`).
    """
    fusion_entries: dict = {}
    dex_json = game_dir / "Data" / "pokedex" / "dex.json"

    if not dex_json.is_file():
        return fusion_entries

    try:
        content = dex_json.read_text(encoding="utf-8", errors="replace")
        records = json.loads(content)
    except (OSError, json.JSONDecodeError) as exc:
        log.warning("Cannot read %s: %s", dex_json, exc)
        return fusion_entries

    for rec in records:
        sprite = rec.get("sprite", "")
        entry_text = _clean_entry_text(rec.get("entry", ""))
        if not entry_text or not sprite:
            continue

        # Sprite format: "head.body.png" or "head.body_variant.png"
        base = sprite.rsplit(".png", 1)[0] if sprite.endswith(".png") else sprite
        parts = base.split(".", 1)
        if len(parts) != 2:
            continue

        try:
            head_id = int(parts[0])
            # Body may contain variant suffix like "4a"; strip non-digits
            body_num = re.match(r"(\d+)", parts[1])
            if not body_num:
                continue
            body_id = int(body_num.group(1))
        except ValueError:
            continue

        head_name = id_map.get(head_id)
        body_name = id_map.get(body_id)
        if not head_name or not body_name:
            continue

        pair = (head_name, body_name)
        # Keep the first entry for each pair (skip duplicates)
        if pair not in fusion_entries:
            fusion_entries[pair] = entry_text

    if fusion_entries:
        log.info("Parsed %d fusion entries from %s", len(fusion_entries), dex_json.name)
    return fusion_entries


# ---------------------------------------------------------------------------
# TTS generation
# ---------------------------------------------------------------------------

def _generate_pyttsx3(text: str, out_wav: Path, speech_rate: int = 130,
                      voice_index: int = 0) -> None:
    """Synthesise *text* with pyttsx3 and save as WAV to *out_wav*.

    *speech_rate* is the words-per-minute speaking speed passed to SAPI.
    130 wpm is slightly slower than natural speech, which gives the measured,
    deliberate cadence associated with the classic Pokédex narrator.
    """
    engine = pyttsx3.init()
    voices = engine.getProperty("voices")
    if voices and voice_index < len(voices):
        engine.setProperty("voice", voices[voice_index].id)
    engine.setProperty("rate", speech_rate)
    engine.setProperty("volume", 1.0)
    engine.save_to_file(text, str(out_wav))
    engine.runAndWait()
    engine.stop()


def _generate_gtts(text: str, out_mp3: Path) -> None:
    """Synthesise *text* with gTTS and save as MP3 to *out_mp3*."""
    tts = gTTS(text=text, lang="en", slow=False)
    tts.save(str(out_mp3))


# ---------------------------------------------------------------------------
# FakeYou TTS  (uses the real "Pokedex (Pokemon, 4Kids)" AI voice model)
# ---------------------------------------------------------------------------
# Same approach as github.com/adriantwarog/Pokedex-RL — calls the FakeYou
# REST API with the community-trained Pokédex Dexter voice model.

_FAKEYOU_MODEL_TOKEN = "weight_dh8zry5bgkfm0z6nv3anqa9y5"
_FAKEYOU_LOGIN_URL = "https://api.fakeyou.com/v1/login"
_FAKEYOU_INFERENCE_URL = "https://api.fakeyou.com/tts/inference"
_FAKEYOU_JOB_URL = "https://api.fakeyou.com/tts/job/{}"
_FAKEYOU_AUDIO_BASE = "https://storage.googleapis.com/vocodes-public"

# Polling settings for waiting on FakeYou job completion
_FAKEYOU_POLL_INTERVAL = 5      # seconds between status checks
_FAKEYOU_MAX_WAIT = 300         # give up after this many seconds (anonymous queue can be slow)
_FAKEYOU_RATE_LIMIT_WAIT = 15   # pause when rate-limited


def _sanitize_fakeyou_cookie(raw: str) -> str:
    """Extract the session token value from various cookie formats.

    Users may pass the cookie in different ways:
      - Plain token value:       ``abc123``
      - With session= prefix:    ``session=abc123``
      - Full cookie header:      ``session=abc123; _ga=GA...``
      - With Cookie: prefix:     ``Cookie: session=abc123``

    This helper normalises all of these to the bare token value.
    """
    raw = raw.strip()
    if not raw:
        return ""

    # Strip optional "Cookie:" prefix (case-insensitive)
    if raw.lower().startswith("cookie:"):
        raw = raw[len("cookie:"):].strip()

    # If the string contains "session=", extract that cookie's value
    match = re.search(r"(?:^|;\s*)session=([^;]+)", raw)
    if match:
        return match.group(1).strip()

    # Otherwise treat the whole thing as a bare token value
    return raw


def _fakeyou_login(username: str, password: str) -> str:
    """Log in to FakeYou and return the session cookie token.

    Calls the ``/v1/login`` endpoint with the given credentials and
    extracts the ``session`` cookie from the response.

    Raises
    ------
    RuntimeError
        If login fails or no session cookie is returned.
    """
    resp = _requests.post(
        _FAKEYOU_LOGIN_URL,
        json={"username_or_email": username, "password": password},
        headers={"Content-Type": "application/json", "Accept": "application/json"},
        timeout=30,
    )

    if resp.status_code == 401:
        raise RuntimeError(
            "FakeYou login failed: invalid username/email or password."
        )
    resp.raise_for_status()

    result = resp.json()
    if not result.get("success"):
        raise RuntimeError(
            f"FakeYou login failed: "
            f"{result.get('error_reason', 'unknown error')}"
        )

    # Extract session cookie from the response Set-Cookie header
    session_cookie = resp.cookies.get("session", "")
    if not session_cookie:
        # Try parsing from raw Set-Cookie header as fallback
        set_cookie = resp.headers.get("set-cookie", "")
        match = re.search(r"session=([^;]+)", set_cookie)
        if match:
            session_cookie = match.group(1)

    if not session_cookie:
        raise RuntimeError(
            "FakeYou login succeeded but no session cookie was returned."
        )

    log.info("FakeYou: logged in successfully as '%s'", username)
    return session_cookie


def _generate_fakeyou(text: str, out_wav: Path, cookie: str = "") -> None:
    """Synthesise *text* with the FakeYou Pokédex voice model.

    Submits a TTS inference job, polls until complete, and downloads
    the resulting WAV file to *out_wav*.

    Parameters
    ----------
    text : str
        The Pokédex entry text to speak.
    out_wav : Path
        Destination file path (WAV format).
    cookie : str
        Optional FakeYou session cookie for priority queue access.
        Without it, jobs go into the anonymous (slower) queue.
    """
    headers = {"Content-Type": "application/json", "Accept": "application/json"}
    if cookie:
        headers["Cookie"] = f"session={cookie}"

    # 1. Submit TTS inference job
    payload = {
        "tts_model_token": _FAKEYOU_MODEL_TOKEN,
        "uuid_idempotency_token": str(uuid.uuid4()),
        "inference_text": text,
    }
    resp = _requests.post(
        _FAKEYOU_INFERENCE_URL,
        headers=headers,
        json=payload,
        timeout=30,
    )
    resp.raise_for_status()
    result = resp.json()

    if not result.get("success"):
        raise RuntimeError(
            f"FakeYou inference request failed: "
            f"{result.get('error_reason', 'unknown error')}"
        )

    job_token = result.get("inference_job_token")
    if not job_token:
        raise RuntimeError("FakeYou returned no inference_job_token")

    log.debug("FakeYou job submitted: %s", job_token)

    # 2. Poll until the job finishes
    elapsed = 0
    status = "unknown"
    while elapsed < _FAKEYOU_MAX_WAIT:
        time.sleep(_FAKEYOU_POLL_INTERVAL)
        elapsed += _FAKEYOU_POLL_INTERVAL

        try:
            poll_resp = _requests.get(
                _FAKEYOU_JOB_URL.format(job_token),
                headers=headers,
                timeout=30,
            )
        except _requests.RequestException as exc:
            log.debug("FakeYou poll request failed: %s", exc)
            continue
        if poll_resp.status_code == 429:
            log.debug("FakeYou rate-limited, waiting %ds…", _FAKEYOU_RATE_LIMIT_WAIT)
            time.sleep(_FAKEYOU_RATE_LIMIT_WAIT)
            elapsed += _FAKEYOU_RATE_LIMIT_WAIT
            continue
        poll_resp.raise_for_status()
        state = poll_resp.json().get("state", {})
        status = state.get("status", "unknown")

        log.debug("  Job %s status: %s (%.0fs)", job_token, status, elapsed)

        if status == "complete_success":
            wav_path = state.get("maybe_public_bucket_wav_audio_path")
            if not wav_path:
                raise RuntimeError("FakeYou job succeeded but returned no audio path")

            # 3. Download the WAV file
            audio_url = f"{_FAKEYOU_AUDIO_BASE}{wav_path}"
            try:
                audio_resp = _requests.get(audio_url, timeout=60)
                audio_resp.raise_for_status()
            except _requests.RequestException as exc:
                raise RuntimeError(
                    f"Failed to download FakeYou audio from {audio_url}: {exc}"
                ) from exc
            out_wav.write_bytes(audio_resp.content)
            log.debug("Downloaded FakeYou audio: %s", out_wav)
            return

        if status in ("dead", "attempt_failed", "complete_failure"):
            raise RuntimeError(f"FakeYou job failed with status: {status}")

        # "pending", "started", "attempt_pending" → keep polling

    raise RuntimeError(
        f"FakeYou job timed out after {_FAKEYOU_MAX_WAIT}s (last status: {status})"
    )


def _apply_dexter_effect(audio: "AudioSegment") -> "AudioSegment":
    """
    Apply post-processing to make the voice sound like Dexter from the
    classic Pokémon anime:

    1. High-pass filter  — removes bass, gives a thin, broadcast-radio quality
    2. Low-pass filter   — softens harsh high frequencies
    3. Echo overlay      — adds the characteristic resonant 'robot' quality
    4. Normalise         — ensures consistent loudness
    """
    # Band-pass simulation: cut below 350 Hz and above 4 000 Hz
    audio = audio.high_pass_filter(350)
    audio = audio.low_pass_filter(4000)

    # Subtle echo: quieter copy delayed by ~35 ms gives robotic resonance
    echo = audio - 13          # 13 dB quieter
    audio = audio.overlay(echo, position=35)

    audio = normalize(audio)
    return audio


def generate_voice_file(text: str, dest_ogg: Path, backend: str = "auto",
                        voice_index: int = 0,
                        fakeyou_cookie: str = "") -> bool:
    """
    Generate a single voiced OGG file at *dest_ogg*.

    Returns True on success, False on failure.
    """
    dest_ogg = Path(dest_ogg)
    dest_ogg.parent.mkdir(parents=True, exist_ok=True)

    with tempfile.TemporaryDirectory() as tmp_dir:
        tmp = Path(tmp_dir)

        # ---- step 1: raw TTS -----------------------------------------------
        raw_path: Path | None = None
        used_fakeyou = False

        if backend == "fakeyou" and HAS_REQUESTS:
            raw_path = tmp / "raw.wav"
            try:
                _generate_fakeyou(text, raw_path, cookie=fakeyou_cookie)
                used_fakeyou = True
            except Exception as exc:
                log.error("FakeYou failed: %s", exc)
                raw_path = None

        if raw_path is None and backend in ("pyttsx3", "auto") and HAS_PYTTSX3:
            raw_path = tmp / "raw.wav"
            try:
                _generate_pyttsx3(text, raw_path, voice_index=voice_index)
            except Exception as exc:
                log.debug("pyttsx3 failed: %s", exc)
                raw_path = None

        if raw_path is None and backend in ("gtts", "auto") and HAS_GTTS:
            raw_path = tmp / "raw.mp3"
            try:
                _generate_gtts(text, raw_path)
            except Exception as exc:
                log.debug("gTTS failed: %s", exc)
                raw_path = None

        if raw_path is None or not raw_path.exists():
            log.error(
                "No TTS backend produced output.  "
                "Install pyttsx3 (offline) or gTTS (online), "
                "or use --backend fakeyou (requires internet)."
            )
            return False

        # ---- step 2: audio effects + export --------------------------------
        # FakeYou already uses the real Pokédex AI voice model so the Dexter
        # post-processing effects are unnecessary and would degrade quality.
        if HAS_PYDUB and HAS_FFMPEG:
            try:
                audio = AudioSegment.from_file(str(raw_path))
                if not used_fakeyou:
                    audio = _apply_dexter_effect(audio)
                audio.export(
                    str(dest_ogg),
                    format="ogg",
                    parameters=["-q:a", "5"],
                )
            except Exception as exc:
                log.error("pydub processing failed: %s", exc)
                # Fall back to raw copy
                shutil.copy(str(raw_path), str(dest_ogg.with_suffix(raw_path.suffix)))
                return True
        else:
            # No pydub or no ffmpeg — save the raw audio without Dexter effects.
            # The user has already been warned at startup; no per-file message needed.
            fallback = dest_ogg.with_suffix(raw_path.suffix)
            shutil.copy(str(raw_path), str(fallback))

    return True


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def list_voices() -> int:
    if not HAS_PYTTSX3:
        print("pyttsx3 is not installed.  Run:  pip install pyttsx3")
        return 1
    engine = pyttsx3.init()
    voices = engine.getProperty("voices")
    if not voices:
        print("No voices found.")
        engine.stop()
        return 0
    print("Available pyttsx3 voices:")
    for i, v in enumerate(voices):
        print(f"  [{i}]  {v.name}")
        print(f"        id: {v.id}")
    engine.stop()
    return 0


def build_arg_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        description="Generate Pokédex voice-over audio files for the KIF mod.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    p.add_argument(
        "--game-dir",
        metavar="PATH",
        help="Path to your KIF game root directory (contains Data/ and/or PBS/, Mods/, etc.).",
    )
    p.add_argument(
        "--pbs-file",
        metavar="PATH",
        help=(
            "Explicit path to a PBS pokemon.txt file.  "
            "Use this if your game stores PBS data in a non-standard location."
        ),
    )
    p.add_argument(
        "--species",
        metavar="NAME",
        help="Generate a file for one species only (e.g. BULBASAUR).",
    )
    p.add_argument(
        "--fusions",
        action="store_true",
        default=True,
        help="Generate voice files for fusion Pokédex entries (default: on).",
    )
    p.add_argument(
        "--no-fusions",
        action="store_true",
        help="Skip fusion Pokédex entries — generate only regular Pokémon.",
    )
    p.add_argument(
        "--overwrite",
        action="store_true",
        help="Overwrite existing audio files (default: skip).",
    )
    p.add_argument(
        "--backend",
        choices=["auto", "pyttsx3", "gtts", "fakeyou"],
        default="auto",
        help=(
            "TTS backend.  'fakeyou' (RECOMMENDED) uses the FakeYou AI voice "
            "model trained on the real anime Pokédex voice.  'auto' tries "
            "pyttsx3 then gTTS as offline/generic fallbacks (default: auto)."
        ),
    )
    p.add_argument(
        "--fakeyou-cookie",
        metavar="COOKIE",
        help=(
            "FakeYou session cookie for authenticated (priority-queue) access.  "
            "May also be set via the FAKEYOU_COOKIE environment variable.  "
            "Without this, jobs use the anonymous queue which is slower."
        ),
    )
    p.add_argument(
        "--fakeyou-username",
        metavar="USER",
        help=(
            "FakeYou account username or email.  Used with --fakeyou-password "
            "to log in automatically and obtain a session cookie."
        ),
    )
    p.add_argument(
        "--fakeyou-password",
        metavar="PASS",
        help=(
            "FakeYou account password.  Used with --fakeyou-username "
            "to log in automatically.  May also be set via the "
            "FAKEYOU_PASSWORD environment variable."
        ),
    )
    p.add_argument(
        "--voice",
        type=int,
        default=0,
        metavar="INDEX",
        help="pyttsx3 voice index (see --list-voices).  Default: 0.",
    )
    p.add_argument(
        "--list-voices",
        action="store_true",
        help="Print available pyttsx3 voices and exit.",
    )
    p.add_argument(
        "--verbose", "-v",
        action="store_true",
        help="Show debug output.",
    )
    return p


def main(argv=None) -> int:
    parser = build_arg_parser()
    args = parser.parse_args(argv)

    if args.verbose:
        log.setLevel(logging.DEBUG)
        logging.getLogger().setLevel(logging.DEBUG)

    # ---- list-voices shortcut -----------------------------------------------
    if args.list_voices:
        return list_voices()

    # ---- validate required args ---------------------------------------------
    if not args.game_dir:
        parser.error("--game-dir is required (unless using --list-voices).")

    game_dir = Path(args.game_dir)
    if not game_dir.is_dir():
        log.error("Game directory not found: %s", game_dir)
        return 1

    # ---- check at least one TTS backend is available ------------------------
    fakeyou_cookie = args.fakeyou_cookie or os.environ.get("FAKEYOU_COOKIE", "")
    fakeyou_cookie = _sanitize_fakeyou_cookie(fakeyou_cookie)

    # FakeYou login: obtain a fresh session cookie from username/password
    fakeyou_user = args.fakeyou_username or os.environ.get("FAKEYOU_USERNAME", "")
    fakeyou_pass = args.fakeyou_password or os.environ.get("FAKEYOU_PASSWORD", "")
    if fakeyou_user and fakeyou_pass and not fakeyou_cookie:
        if not HAS_REQUESTS:
            log.error(
                "FakeYou login requires the 'requests' package.\n"
                "Run:  pip install requests"
            )
            return 1
        try:
            fakeyou_cookie = _fakeyou_login(fakeyou_user, fakeyou_pass)
        except RuntimeError as exc:
            log.error("FakeYou login failed: %s", exc)
            return 1

    # Resolve --no-fusions override
    do_fusions = args.fusions and not args.no_fusions

    if args.backend == "fakeyou":
        if not HAS_REQUESTS:
            log.error(
                "FakeYou backend requires the 'requests' package.\n"
                "Run:  pip install requests"
            )
            return 1
        if fakeyou_cookie:
            log.info("FakeYou: using authenticated session (cookie provided)")
        else:
            log.info(
                "FakeYou: no cookie provided — using anonymous queue (slower).\n"
                "  Set FAKEYOU_COOKIE env var or use --fakeyou-cookie for "
                "priority access."
            )
    elif not HAS_PYTTSX3 and not HAS_GTTS:
        log.error(
            "No TTS backend found.  "
            "Run:  pip install pyttsx3       (offline, generic voice)\n"
            "  or: pip install gTTS          (online, generic voice)\n"
            "  or: pip install requests      (for --backend fakeyou — "
            "RECOMMENDED, real anime voice)"
        )
        return 1

    if not HAS_PYDUB:
        log.warning(
            "pydub is not installed — Dexter audio effects will be skipped.\n"
            "Run:  pip install -r tools/requirements.txt\n"
            "Also ensure ffmpeg is installed and on your PATH."
        )
    elif not HAS_FFMPEG:
        log.warning(
            "ffmpeg not found on PATH — Dexter audio effects will be skipped.\n"
            "Install ffmpeg and add it to your PATH:\n"
            "  Windows: https://ffmpeg.org/download.html  (add the bin/ folder to PATH)\n"
            "           or:  winget install ffmpeg  /  choco install ffmpeg\n"
            "  macOS:   brew install ffmpeg\n"
            "  Linux:   sudo apt install ffmpeg\n"
            "After installing, open a new terminal so the updated PATH takes effect."
        )

    # ---- resolve output directory -------------------------------------------
    output_dir = game_dir / "Mods" / "pokedex_voice_over" / "Audio"
    output_dir.mkdir(parents=True, exist_ok=True)
    log.info("Output directory: %s", output_dir)

    # ---- parse Pokédex data -------------------------------------------------
    # Strategy: try Data/species.dat (KIF) first, then PBS/pokemon.txt (PIF),
    # then an explicit --pbs-file if given.
    all_entries: dict = {}
    species_id_map: dict = {}
    species_dat = game_dir / "Data" / "species.dat"

    # 1. KIF Data/species.dat (requires rubymarshal)
    if species_dat.is_file():
        if HAS_RUBYMARSHAL:
            all_entries = parse_species_dat(species_dat)
            species_id_map = build_species_id_map(species_dat)
        else:
            log.info(
                "Found %s but rubymarshal is not installed.\n"
                "  Run:  pip install rubymarshal\n"
                "  to enable reading Pokédex data directly from the KIF game data.",
                species_dat,
            )

    # 2. PBS/pokemon.txt (vanilla PIF or manually extracted)
    if not all_entries:
        pbs_file = Path(args.pbs_file) if args.pbs_file else game_dir / "PBS" / "pokemon.txt"
        if pbs_file.is_file():
            all_entries = parse_pbs_pokemon(pbs_file)

    # 3. Give up with a helpful error
    if not all_entries:
        has_species_dat = species_dat.is_file()
        if has_species_dat and not HAS_RUBYMARSHAL:
            log.error(
                "No Pokédex entries found.\n"
                "  Your game has Data/species.dat but rubymarshal is not installed.\n"
                "  Fix:  pip install rubymarshal"
            )
        else:
            log.error(
                "No Pokédex entries found.\n"
                "  Make sure --game-dir points to the KIF game root directory\n"
                "  (the folder that contains Game.exe and the Data/ directory).\n"
                "  Checked:\n"
                "    - %s  (not found)\n"
                "    - %s  (not found)\n"
                "  If your PBS file is elsewhere, use --pbs-file to specify its path.",
                species_dat,
                game_dir / "PBS" / "pokemon.txt",
            )
        return 1

    # ---- filter to single species if requested ------------------------------
    if args.species:
        key = args.species.strip().upper()
        if key not in all_entries:
            log.error("Species '%s' not found in Pokédex data.", key)
            return 1
        all_entries = {key: all_entries[key]}

    # ---- process regular Pokémon entries ------------------------------------
    generated = skipped = failed = 0

    for species_name, entry_text in sorted(all_entries.items()):
        dest = output_dir / f"dex_{species_name}.ogg"

        if not args.overwrite and dest.exists():
            log.debug("Skipping %s (already exists)", dest.name)
            skipped += 1
            continue

        log.info("Generating: %s", dest.name)
        log.debug("  Text: %s", entry_text[:80])

        ok = generate_voice_file(
            entry_text,
            dest,
            backend=args.backend,
            voice_index=args.voice,
            fakeyou_cookie=fakeyou_cookie,
        )
        if ok:
            generated += 1
        else:
            failed += 1

    # ---- process fusion entries ---------------------------------------------
    if do_fusions:
        fusion_entries: dict = {}

        # Try KIF JSON fusion data first
        if species_id_map:
            fusion_entries = parse_kif_fusion_json(game_dir, species_id_map)

        # Fall back to PBS fusion files
        if not fusion_entries:
            fusion_entries = parse_fusion_entries(game_dir)

        if not fusion_entries:
            log.info(
                "No fusion Pokédex entries found.  "
                "KIF may use auto-generated fusion descriptions that are not "
                "stored in data files."
            )
        for (sp1, sp2), entry_text in sorted(fusion_entries.items()):
            dest = output_dir / f"dex_{sp1}_{sp2}.ogg"

            if not args.overwrite and dest.exists():
                skipped += 1
                continue

            log.info("Generating fusion: %s", dest.name)
            ok = generate_voice_file(
                entry_text,
                dest,
                backend=args.backend,
                voice_index=args.voice,
                fakeyou_cookie=fakeyou_cookie,
            )
            if ok:
                generated += 1
            else:
                failed += 1

    # ---- summary ------------------------------------------------------------
    print(
        f"\nDone — generated: {generated}, skipped: {skipped}, failed: {failed}"
    )
    print(f"Audio files saved to: {output_dir}")
    return 0 if failed == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
